### ISSUE TITLE
[Feat]: add a ci/cd bats test for s3fuse

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#1029]
### Is your feature request related to a problem? Please describe.

https://github.com/s3fs-fuse/s3fs-fuse
^ this is a viable option for zot + s3 so that it can be used as a local filesystem. 

### Describe the solution you'd like

Can this be added in our ci/cd bats tests?

**Comment by andaaron** [comment]
No longer relevant as we support S3 using libraries.

As a side note S3 dedupe uses empty files for duplicates, so mounting the files locally won't help anyone.
