### ISSUE TITLE
[feat]: use canSkipImage() in sync onDemand

### ISSUE THREAD

**Issue by peusebiu** [project-zot/zot#1208]
### zot version

main

### Describe the bug

in sync on demand we try to sync every time a newer version of the image:tag, syncing the same image again if there is no updated on upstream.

we should use canSkipImage() in sync onDemand.

### To reproduce

1. Configuration
2. Client tool used
3. Seen error

**Comment by andaaron** [comment]
Implemented in https://github.com/project-zot/zot/pull/1234
