### ISSUE TITLE
[Feat]: cleanup error msgs

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#1235]
### Is your feature request related to a problem? Please describe.

We print too many msgs at Error level even when we know how to handle them.

```
func inner() {
  err := do_something()
  if err != nil {
     log("this error")
     return err
  }
}

func outer() {
  err := inner()
  if err != nil {
      // maybe I know how to handle this error
  }
}
```

We have patterns like this in the code and we should avoid printing errors at Error level in `inner()`-type funcs so that we don't pollute the logs.

### Describe the solution you'd like

Clean up our logs. They are very misleading especially the Error-level ones.

**Comment by andaaron** [comment]
This was solved in https://github.com/project-zot/zot/pull/1273.
I don't think we have other such cases. If we do, let's reopen.
