### ISSUE TITLE
Cleanup: move pkg/extensions/search/common/oci_layout.go under pkg/test/

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#1270]
Once #1269 is done, the only usage of OciLayoutUtils remains in extractImageDetails (resolver.go) and in tests.
Both OciLayoutUtils and extractImageDetails cand be moved to the pkg/test package.
Also remove `userAvailableRepos` (resolvers.go) entirely.

`extractImageDetails` from resolvers.go may be moved into a method of OciLayoutUtils in the new location. Note extractImageDetails has unit tests, so those should be moved, adapted as well.

OciLayoutUtils was used extensively by the GraphQL API before RepoDB was implemented.

**Comment by nicoldr** [comment]
Closing this as it is solved in #1325
