### ISSUE TITLE
Please implement support for registry.k8.io and make it the default for Kubernetes 

### ISSUE THREAD

**Issue by chris-short** [project-zot/zot#1283]
### Is your feature request related to a problem? Please describe.

I tried to get zot working with the now default upstream Kubernetes image repo registry.K8s.io. As K8s.GCR.io is now being redirected, many folks’ implementations might break as registry.k8s.io does not support `_catalog`. Learn more here: https://k8s.io/image-registry-redirect (the bare registry url redirects to GitHub repo with the implementation)

### Describe the solution you'd like

Zot to make registry.k8s.io available as the default Kubernetes repository.

### Describe alternatives you've considered

N/A

### Additional context

k8s.gcr.io is being removed eventually

**Comment by rchincha** [comment]
@chris-short thx for bringing this to our attention, looking into it.

**Comment by rchincha** [comment]
https://kubernetes.io/blog/2023/03/10/image-registry-redirect/
