### ISSUE TITLE
[Refactor]: simplify pkg/meta/repodb* code structure

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#1284]
### Is your feature request related to a problem? Please describe.

Currently, over a tranche of changes, pkg/meta/repodb* codebase is unnecessarily nested/complicated. We should flatten and make it idiomatic go.

**Comment by andaaron** [comment]
Let's do this in multiple steps. For the first step/PR:

1. Code for initializing the DB driver should be outside a specific repodb implementation
```
 	repoDB, err := bolt.Open(path.Join(params.RootDir, "repo.db"), perms, &bolt.Options{Timeout: time.Second * 10})
	if err != nil {
		return nil, err
	}
````
The repoDB object in the example above could also be injected in the NewBoltDBWrapper for example.
2. `pkg/meta/repodb/dynamodb-wrapper/iterator/dynamo_iterator.go` should be accessible for import from the same place for both repodb and userdb.
3. `pkg/meta/userdb/dynamodb-wrapper/params/parameters.go` should also be accessible for import from the same place for both repodb and userdb.

For common code, we can have it under `pkg/meta`, `pkg/meta/dynamo` and `pkg/meta/boltdb`.
We will later restructure the rest of the repodb/userdb code to match this folder structure proposed in the description of this issue.
