### ISSUE TITLE
feat: s3 remote storage when use zot to run as a mirror registry?

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#1297]
Thanks for your work, have any info for s3 remote storage when use zot to run as a mirror registry?  It's not support in today.

_Originally posted by @liangyuanpeng in https://github.com/project-zot/project-zot.github.io/pull/72#pullrequestreview-1307446266_

**Comment by peusebiu** [comment]
Hello,

s3 + sync is currently not supported because we are syncing images in a temporary local oci layout before committing them in the storage using storage APIs.

For that to work we must get rid of using containers/image library and implement our own copy.Image().

**Comment by liangyuanpeng** [comment]
> so you want storage for mirroring to be s3 remote storage instead of local?

Yes, it's would be great if it can be work.

**Comment by peusebiu** [comment]
fixed in #https://github.com/project-zot/zot/commit/3c8da6e6fc0739e632c5a9dfc4857d628052c346
