### ISSUE TITLE
[Bug]: RepoDB should read-lock imageStore before using GetIndexContent() and GetBlobContent()

### ISSUE THREAD

**Issue by peusebiu** [project-zot/zot#1316]
### zot version

main

### Describe the bug

example: https://github.com/project-zot/zot/blob/main/pkg/meta/repodb/storage_parsing.go#L236

should look like this: https://github.com/project-zot/zot/blob/main/pkg/extensions/sync/utils.go#L315

### To reproduce

1. Configuration
2. Client tool used
3. Seen error

**Comment by liangyuanpeng** [comment]
@peusebiu  Can i work for it? It's seems like just need create a time.Time to use for lock and use is around imageStore.GetBlobContent.

**Comment by peusebiu** [comment]
Helo Lian, yes that's right, just a time.Time and locks around GetBlobContent and GetIndexContent

There is nothing to reproduce:D, without this change it will race sometime.
The imagestore can be write locked while we read it.
