### ISSUE TITLE
[Bug]: listening port chosen by kernel is printed to the console instead of being logged

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#1322]
### zot version

v2.0.0-rc3

### Describe the bug

The port selected automatically by the kernel in issue https://github.com/project-zot/zot/issues/717 is printed to the console instead of the logs. See https://github.com/project-zot/zot/pull/1260.

### To reproduce

See implementation of https://github.com/project-zot/zot/issues/717 in https://github.com/project-zot/zot/pull/770.

### Expected behavior

Instead of printing to the console, this information should be shown in the zot logs.
Preferably as part of the config json shown when zot starts. If that is not possible, it should be shown in a separate log message.

**Comment by thesayyn** [comment]
It’s also printed to the console if you configured your logger properly.

**Comment by andaaron** [comment]
Fixed in https://github.com/project-zot/zot/pull/1339
