### ISSUE TITLE
Make sure our CI job tests the sync feature with the most used upstream registry services

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#1379]
Make sure we have blackbox tests for zot sync configured to point to these types of upstream services:
- Dockerhub
- registry.k8s.io
- Amazon ECR
- Google Container Registry
- Azure Container Registry

**Comment by andaaron** [comment]
@rchincha please review the list in the description.

**Comment by peusebiu** [comment]
after syncing, make sure they can be run with docker.

**Comment by andaaron** [comment]
Done in #1414
