### ISSUE TITLE
[Feat]: migrate to OCI image spec v1.1.0-rc3

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#1406]
### Is your feature request related to a problem? Please describe.

https://github.com/oras-project/oras-go/issues/494
^ this is a good summary of required changes, and we need to coordinate with the oras project anyways.

**Comment by FeynmanZhou** [comment]
May I know the ETA date for the Zot v2.0.0 release?

**Comment by andaaron** [comment]
We switch to the source repo for the new spec in https://github.com/project-zot/zot/pull/1468
So this item is done.

@rchincha I think we can do a v2.0.0-rc5 release for this change?

**Comment by andaaron** [comment]
Let's close this as we already implemented RC3 and we're working on RC4.
