### ISSUE TITLE
[Feat]: referrers API MUST respond with the response header `OCI-Subject: true`

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#1410]
https://github.com/opencontainers/distribution-spec/commit/16cc054de70442ea08e1aa269cee1c6cda5e7c96

```
When processing a request for an image or artifact manifiest with the `subject` field, a registry implementation that supports the [referrers API](#listing-referrers) MUST respond with the response header `OCI-Subject-Processed: true` to indicate to the client that the registry understands the request's `subject`.
```

**Comment by laurentiuNiculae** [comment]
I think this is outdated. [This ](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pushing-manifests-with-subject) is from main branch of the distribution spec. We should return the actual digest from the subject field.
