### ISSUE TITLE
[Bug]: Tag UI page main content not updated when changing the OS/Arch

### ISSUE THREAD

**Issue by rgl** [project-zot/zot#1417]
### zot version

2.0.0-rc4

### Describe the bug

When changing the OS/Arch the central content tab/content (i.e. in the following screenshot, its the `Layers` tab) is not updated.

### To reproduce

1. Open the UI.
2. Select an image.
3. Select a image tag (must be multi-arch).
4. Select a different OS/Arch.
5. Notice that the `Layers` tab content is not updated. See the highlights in the screenshot, the bottom highlight should have show `arm64` instead of `amd64`.  

### Screenshots

![zot-tag-layers-refresh-bug](https://user-images.githubusercontent.com/43356/236010658-499aecae-f3f4-4867-9f99-8d2b79b6bc65.png)

**Comment by rchincha** [comment]
@rgl Thanks for the issue. We are redesigning this page a little bit - will let you know once ready.

**Comment by raulkele** [comment]
@rgl Thanks for reporting the bug, the issue is fixed in project-zot/zui#349 and will be in the next rc release. You can also configure zot to pull the top of main latest version of the ui.
In the future, consider reporting UI related bugs in the UI repository project-zot/zui for better visibility.
