### ISSUE TITLE
[Feat]: propagate error msgs to the client (but be mindful of OCI dist-spec)

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#1418]
### Is your feature request related to a problem? Please describe.

`zot` performs several validations and when validations fail, we rely on the HTTP status code, so far so good. However, would be more useful if we propagate the detailed error msg back to client.

https://github.com/opencontainers/distribution-spec/blob/main/spec.md#error-codes

https://github.com/project-zot/zot/issues/1411
^ also see

**Comment by tripathysagar** [comment]
Please, assign me this issue. And suggest me a rough roadmap to follow.

**Comment by rchincha** [comment]
Thanks @tripathysagar 

All "external" interactions happen via pkg/api/routes.go. So would do a deep dive from there and improve the error msgs instead of just returning the high-level error code.

**Comment by tripathysagar** [comment]
Hello @rchincha , I am not able to do much progress on this issue due to prior commitments. Please mark the ticket as unassigned so that anybody else can pick it up.

**Comment by andaaron** [comment]
This should be resolved starting with https://github.com/project-zot/zot/pull/1681
