### ISSUE TITLE
[Bug]: ZUI does not work with LDAP

### ISSUE THREAD

**Issue by bfreidank** [project-zot/zot#1423]
### zot version

2.0.0-RC4

### Describe the bug

Auth to UI failing when using LDAP as auth source.

### To reproduce

1. Login to https://server-fqdn:5000
2. Get prompted for credentials
3. Fails to login and re-prompts for credentials
4. zot.log shows: 

```json
{"level":"error","error":"illegal base64 data at input byte 0","goroutine":191,"caller":"zotregistry.io/zot/pkg/api/authn.go:216","time":"2023-05-05T17:57:54.783118655Z","message":"failed to parse authorization header"}
```

### Expected behavior

Login successfully

**Comment by rchincha** [comment]
@bfreidank Looking into this. UI is a new feature in 2.0.0 and we are fixing some issues in UI+authN interactions.

**Comment by bfreidank** [comment]
@rchincha Testing the following scenario to get some more information for troubleshooting

Steps taken:
- Removed "anonymousPolicy": ["read"] from http.accessControl.repositories.** and restarted server
- Opened Edge Chromium DevTools, select **Application** from more tabs and expand Local Storage\https://server-fqdn:5000
- Navigated to https://server-fqdn:5000/v2/ and login when prompted. This logs in, loads blank page and doesn't re-prompt for login.
- Noticed **token** Key shows the Value of **-** instead of a base64 version of the credential for the Basic Auth that is requested.
- Navigated to https://server-fqdn:5000/home and was prompted for credentials repeatedly.
- Generated base64 value of credentials using the following to simulate basic auth:
```
echo -n 'username:password' | base64
```
- Adjusted the **token** value to the base64 value created in previous step. Reloaded the page and was able to get https://server-fqdn:5000/home to load. Additionally I was able to navigate to additional pages using the injected **token** Key value.
- Removed **token** Key from **Local Storage** section, re-prompted for auth and failed as expected with **token** Key Value being set to **-**

**Comment by raulkele** [comment]
Hello @bfreidank, thank you for reporting the bug. A PR was merged on ZUI yesterday which I believe solves this issue (project-zot/zui#350) you can test it out by rebuilding the zot binary with the ZUI_VERSION='' argument which will cause zot to pull the top of main version of zui. Please let me know if the issue persists. 
For future reference, please consider opening UI related issues directly on the UI repository project-zot/zui, for better visibilty.
