### ISSUE TITLE
[Feat]: Full ondemand passthrough cache

### ISSUE THREAD

**Issue by Poulpatine** [project-zot/zot#1545]
### Is your feature request related to a problem? Please describe.

I'd like to use zot a local registry cache for Gitlab runners.

Usually, my users are using docker images from docker.io or from gitlab.com but they could use other registries and I'd like to avoid having to define a long list of registries in zot configuration.

### Describe the solution you'd like

A new flag in configuration allowing a passthrough  ondemand cache ?

**Comment by andaaron** [comment]
Hi @Poulpatine and thank you for reaching out to us.
The list of servers in zot configuration is a list of servers zot knows it can search for images not found locally.
If they are not in the list, zot does does not know they exist, so it cannot use them.

Passthrough on-demand cache is possible, but you would still need to configure all the registries the zot instance needs to be aware of.

**Comment by Poulpatine** [comment]
Sure I understand what you mean but, wouldn't it be possible to have an automatic mode where, in the image name, everything between <zot_hostname>/ and before second / would be considered as a registry "as is" ?

Unless I miss something, the "auto" format would be :

<zot_hostname>/<registry_name>/<image_name>

Like  :

zot.mydomain.com/registry.gitlab.com/myproject/myimage:latest -> registry.gitlab.com used as registry
zot.mydomain.com/ghcr.io/otherproject/otherimage:v1 -> ghcr.io used as registry

**Comment by rchincha** [comment]
@Poulpatine we don't want to impose/interpret any conventions since it is not necessarily "one-size-fits-all". Instead, we can add an example under the [examples/](./examples) folder so that you can just copy and paste it. Pls. feel free to submit a PR to capture your proposal - we will look at adding one in any case.

**Comment by Poulpatine** [comment]
Sure, it's done here https://github.com/project-zot/zot/pull/1550

Thanks for your time and for the great product folks :+1:
