### ISSUE TITLE
Project Website

### ISSUE THREAD

**Issue by McCodeman** [project-zot/zot#155]
As a potential user or contributor, I would like to read about the project, find documentation, and browse recent activity on a curated website.

Additional issues can be created and linked back to this parent issue.

Acceptance Criteria:
* [x] Find hosting provider
* [x] Register a DNS name
* [x] Choose static site generator (i.e., hugo, jekyll, gitbook, etc.)
* [ ] Ensure the website has the following content areas
  * [ ] Project summary statement (single short statement that describes the project)
  * [ ] List of major features
  * [ ] Callout and link to latest release
  * [ ] Callout and link to latest media activity (webinars, community meetings, etc.)
  * [ ] Blog list
  * [ ] Getting Started callout
  * [ ] Contributing callout
  * [ ] Links to Project Handles (Twitter, Slack, GitHub)
  * [ ] Documentation
  * [ ] Community (calendar of events, support channels, etc.)
  * [ ] Presentations Link
* [x] Automation to build and deploy the site
* [x] Enable TLS using Let's Encrypt or equivalent (should be supported by hosting provider)
* [ ] Search Engine Optimization (SEO)
* [ ] Tweet and announce site launch

**Comment by rchincha** [comment]
https://anuvu.github.io/zot/

**Comment by JasonvanBrackel** [comment]
We can consider this a checklist for #320

**Comment by rchincha** [comment]
https://zotregistry.io
