### ISSUE TITLE
Establish Communication Channels

### ISSUE THREAD

**Issue by McCodeman** [project-zot/zot#158]
As a user or contributor, I want a dedicated communication channel to work with project maintainers, other contributors, and users.

Acceptance Critera:
* [ ] Evaluate pros/cons of different communication mediums
* [ ] Create a channel for interactive chat
* [ ] Create a channel for announcements
  * Release announcements
  * General project news
  * Security announcements
* [ ] List communication channels in README.md
* [ ] Create automation for adding users to channels (for example, if Slack is used, we may need a slackin for membership invites)
* [ ] Create and publish acceptable use policy for communication channels.
* [ ] Notify users in README.md that comms channels are best effort support.

Possible Communication Channels
* [ ] IRC
* [x] Slack
* [ ] Discord
* [ ] Email Distribution List / Newsgroup
* [ ] Other?

**Comment by rchincha** [comment]
We have three now:
slack, twitter and GH discussions
