### ISSUE TITLE
[Feat] implement GC for S3 storage

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#1582]
At the moment GC is only supported on local storage because it depends on the umoci library. We should also implement GC for S3.

**Comment by rchincha** [comment]
We should really just pull in or implement our own GC code just as the sync code.

**Comment by rchincha** [comment]
Should be fixed with https://github.com/project-zot/zot/pull/1608

**Comment by andaaron** [comment]
Done in https://github.com/project-zot/zot/pull/1656
