### ISSUE TITLE
[Bug]: regclient ci is breaking with default zot settings (gc=true,dedupe=true)

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#1585]
### zot version

v2.0.0-rc5

### Describe the bug

$ make ci-zot
docker run --rm -d -p 5000 \
        --label regclient-ci=true --name regclient-ci-zot \
        -v "$(pwd)/build/zot-config.json:/etc/zot/config.json:ro" \
        ghcr.io/project-zot/zot-linux-amd64:v2.0.0-rc5
637dd191cd832253ea052ce0083b9e1bc6f0f6d4a8cad3e7b9742f69ffdf39d6
./build/ci-test.sh -t localhost:$(docker port regclient-ci-zot 5000 | head -1 | cut -f2 -d:)/test-ci
WARN[0000] Sleeping for backoff                          Host="localhost:49156" Seconds=1.999988674
tag not deleted: localhost:49156/test-ci:v2.1-rc1
make: *** [Makefile:117: ci-zot] Error 1

### To reproduce

1. Configuration
2. Client tool used
3. Seen error

**Comment by andaaron** [comment]
Done in #1610
