### ISSUE TITLE
CONTRIBUTING.md (or asciidoc)

### ISSUE THREAD

**Issue by McCodeman** [project-zot/zot#162]
As a prospective contributor, I want documentation explaining the process and expectations for contributing to this project.

Acceptance Criteria:
* [ ] Create CONTRIBUTING.md (or asciidoc) in root of project.
* [ ] Documentation should include:
  * [ ] How to get started including how to sign a Contributor License Agreement
  * [ ] Pointers to a project architecture document and other relevant information needed to familiarize a new contributor with project internals.
  * [ ] Link to how to setup a development environment.
  * [ ] Instructions on setting up any required accounts
  * [ ] GitHub workflow
  * [ ] How to request review of Issues and PRs
  * [ ] Issue and PR management including Issue Triage

Don't assume that the reader of this document has any background knowledge of the project, acronyms, etc. This document should enable self-service startup for new contributors.

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/blob/main/CONTRIBUTING.md
All other docs at:
https://zotregistry.io
