### ISSUE TITLE
[Feat]: Zot Registry Image Cleanup

### ISSUE THREAD

**Issue by bfreidank** [project-zot/zot#1634]
### Is your feature request related to a problem? Please describe.

Issue where db does not cleanup removed images from data directory or old images that have not been used for x amount of time.

### Describe the solution you'd like

Allow setting for auto image cleanup after x amount of time.
Run cleanup of db if images are not longer located in zot data directories.

### Describe alternatives you've considered

N/A

**Comment by rchincha** [comment]
@bfreidank are you referring to some sort of image retention policy?

**Comment by bfreidank** [comment]
@rchincha yes I am referring to a type of image retention policy.

**Comment by lictw** [comment]
Nice to have feature anyway! Try to make the configuration flexible as possible, Harbor is the good example, for example. Keep by count/date, upload/download, filtering by path/tags, policies composition - all of this is matters!

But from our discussion, it will be great to expose all image stats (that you anyway will store for features above) by API for external clearing purposes, by custom scripts. For example, I have some scenario that don't covered by any cleaning policies (and seems shouldn't be, cause it's very smart/special), I will describe the scenario below. And of course this doesn't mean that I don't need more general, included cleaning policies for others things, I need, just I also have some special.

Imagine tag format `BRANCH.INCREMENT.SHA` like `foo.1.SHA`, `foo.2.SHA`, and every image with that tags also overrides **base branch tag** like `foo` in this example to always follow latest build. So I should found all base tags and for each of them found all tags belongs to this base and keep N of them, N for each base tag, not N for whole image. It's main behavior that can be implemented via registry API, but also, if current registry can let me some date stats (in this case I need last **upload** time of base tag and last download time of base/(first tag)) I can clear unactual trees (base tag + all that belongs to it). One more time - I understand why anyone registry can't do that, it's  to describe why and what API I needs and other people can needs.

Thanks in advance! Zot is very perspective project, unique right now! I already have it for some processes and want to switch on it as on main registry.

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/pull/1866

**Comment by andaaron** [comment]
This was completed in ##1866. Further improvements will be tracked separately.
