### ISSUE TITLE
[Feat]: ability to run behind reverse proxy

### ISSUE THREAD

**Issue by dmaes** [project-zot/zot#1653]
### Is your feature request related to a problem? Please describe.

First of all, thanks for the fantastic work!

I would like to be able to run zot behind a reverse proxy/loadbalancer. I'm only just trying out zot, and at first it seemed to run fine behind a reverse proxy, until I tried enabling openid, and it used `http.address:http.port` in it's redirect_uri, which will obviously fail if you're using something like `http: { address: 0.0.0.0, port: 8443 }` and you're actually accessing it via `https://zot.example.com` via loadbalancer.

### Describe the solution you'd like

Either a config variable for zot to use when building url's, or zot using the `X-Forwarded-Host` header would be nice.

**Comment by dmaes** [comment]
I was looking at the `getRelyingPartyArgs` method in `pkg/api/authn.go` (where to openid redirect uri is build), and it seems it's also basing the scheme on the tls config, which also would not work if one would run zot on http, and proxy on https.

**Comment by rchincha** [comment]
@dmaes Thanks for trying out `zot` and the feedback.

As an alternative, you can deploy `zot` via helm with an ingress and see if that is an option for you.

Meanwhile, @peusebiu can you look at this?

**Comment by dmaes** [comment]
I'm using ldap for authentication in the meantime. That doesn't need to build any (redirect) uri's, and is working fine for the moment (I'm also running bare-metal, not on k8s).

I also saw there are docs an running zot behind a loadbalancer (https://github.com/project-zot/project-zot.github.io/blob/main/docs/articles/clustering.md), so actually this is more a bug in the oidc setup (and possibly other places) then a feature request.

**Comment by rchincha** [comment]
@dmaes pls take a look at PR #1675 and see if it would solve your issue.

**Comment by dmaes** [comment]
@rchincha looks good on first sight, I'll test it next week. Thanks.

**Comment by andaaron** [comment]
This issue has been fixed in #1675, if it not, please reopen.
