### ISSUE TITLE
[Bug]: Multiarch images don't have metadata

### ISSUE THREAD

**Issue by dfr** [project-zot/zot#1666]
### zot version

42f9f78

### Describe the bug

When I push multi-arch images (e.g. quay.io/dougrabson/freebsd-minimal:13.2) to a zot registry, the UI doesn't show any of the metadata (e.g. description, licences etc). If I take one image from the manifest and push it to a different name, the metadata shows up.

It is possible that I am missing something when building the manifests for these images - I noticed that quay.io and docker.io also don't show the image metadata. 

### To reproduce

Copy a multi-arch image using skopeo:
```
skopeo copy --all docker://quay.io/dougrabson/freebsd-minimal@sha256:bf7bb3a8247b6f1b6c88982f932d3f95e0ee9968d3a152c0f2797a672a79e372 docker://myregistry/testimage
```
Navigate to to the testimage page in the UI and observe that description and licenses are not populated

**Comment by dfr** [comment]
Note: I was having problems with quay.io yesterday and the freebsd-minimal image from the repro was an old one without descriptions or licences. I have updated the image and changed the repro to use an explicit hash.

**Comment by laurentiuNiculae** [comment]
Thank you for signaling this issue! I have pushed a [fix](https://github.com/laurentiuNiculae/zot/tree/fix-index-annotations) for it on my branch if you would like to try it out.

**Comment by dfr** [comment]
I think it works but its hard to be sure sine my local zot instance keeps freezing, possibly because of htis?
```
$ ./bin/zot-freebsd-amd64 serve /zboot/zot/config.json                                                                                                       2 ↵
{"level":"info","trivyDownloadURL":"ghcr.io/aquasecurity/trivy-db","time":"2023-08-02T15:13:11+01:00","message":"Config: using default Trivy DB download URL."}
{"level":"info","trivyJavaDownloadURL":"ghcr.io/aquasecurity/trivy-java-db","time":"2023-08-02T15:13:11+01:00","message":"Config: using default Trivy Java DB download URL."}
panic: timeout

goroutine 1 [running]:
zotregistry.io/zot/pkg/cli.newServeCmd.func1(0x1cbd32bf6c00?, {0x1cbd31f64ca0, 0x1, 0x1?})
	zotregistry.io/zot/pkg/cli/root.go:66 +0x11f
github.com/spf13/cobra.(*Command).execute(0x1cbd32bf6c00, {0x1cbd31f64c60, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x1cbd32bf6900)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0x1cbd300061a0?)
	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
	zotregistry.io/zot/cmd/zot/main.go:10 +0x1e
```

**Comment by dfr** [comment]
Ok, I disabled CVE and I'm able to try this out properly. Its much better than before - the image page shows the correct metadata.

The there is a problem in the pages which summarize multiple images (e.g. home or view all). If I load a selection of multiarch images, then the descriptions are all mixed up and change with each refresh. This is the manifest set I'm testing with:
```
for i in static static-debug base base-debug minimal small; do
    skopeo copy --all docker://quay.io/dougrabson/freebsd/13.2/$i docker://myregistry/freebsd/13.2/$i
done
```

**Comment by andaaron** [comment]
> zotregistry.io/zot/pkg/cli.newServeCmd.func1(0x1cbd32bf6c00?, {0x1cbd31f64ca0, 0x1, 0x1?})
> 	zotregistry.io/zot/pkg/cli/root.go:66 +0x11f
> github.com/spf13/cobra.(*Command).execute(0x1cbd32bf6c00, {0x1cbd31f64c60, 0x1, 0x1})
> 	github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
> github.com/spf13/cobra.(*Command).ExecuteC(0x1cbd32bf6900)
> 	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
> github.com/spf13/cobra.(*Command).Execute(0x1cbd300061a0?)
> 	github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
> main.main()
> 	zotregistry.io/zot/cmd/zot/main.go:10 +0x

Off topic, this error is really strange. Even if the download fails it should not crash the pod (assuming you run in kubernetes), it should retry in the background one in a while.

**Comment by dfr** [comment]
That stack trace was from running a bare metal test, not in a container. With CVE enabled, it hangs for about 30secs and then panics.

Running zot in a podman container on FreeBSD doesn't panic, it just repeatedly hangs attempting to fetch the CVE bits and makes the UI near unusable. Workaround is to disable CVE.

**Comment by laurentiuNiculae** [comment]
You're right, I fixed that error. Now we should expect the description of the multi-arch image to be taken in this order:
1. the index descriptor annotations
2. the annotations present in the first manifest listen in the index
3. the labels present in the config associated with the manifest above

If everything is right I think this is resolved.

**Comment by laurentiuNiculae** [comment]
Thank you too!
