### ISSUE TITLE
[Bug]: UI Login not possible with local auth source

### ISSUE THREAD

**Issue by everflux** [project-zot/zot#1670]
### zot version

ghcr.io/project-zot/zot-linux-amd64:v2.0.0-rc6

### Describe the bug

I am currently evaluating zot. During the setup it was very hard to get to a config file that might work since the helm values and website samples contain invalid examples.
After configuring htpasswd as local AuthN source I can't find a way to login in the UI. It is not described in the manuals neither.

### To reproduce

1. Configuration
2. Client tool used
3. Seen error

```
config.json: |-
        {
          "log": { "level": "info" },
          "storage": { 
            "rootDirectory": "/var/lib/registry",
            "dedupe": true,
            "gc": true,
            "gcDelay": "1h",
            "gcInterval": "24h"
          },
          "http": { 
            "address": "0.0.0.0",
            "port": "5000",
            "auth": { "htpasswd": { "path": "/secret/htpasswd" } },
            "realm": "zot",
            "accessControl": {
              "repositories": {
                "**": {
                  "anonymousPolicy": ["read"],
                  "defaultPolicy": ["read", "create", "update"],
                  "policies": [{
                    "users": ["user"],
                    "actions": ["read", "create", "update", "delete"]
                  }]
                }
              },
              "adminPolicy": {
                "users": ["admin"],
                "actions": ["read", "create", "update", "delete"]
              }
            }
          },
          "extensions": {
            "metrics": {
              "enable": true,
              "prometheus": {
                  "path": "/metrics"
              }
            },
            "scrub": {
              "enable": true,
              "interval": "24h"
            },
            "ui": {
              "enable": true
            },
            "search": {
              "cve": {
                "updateInterval": "2h"
              }
            },
            "mgmt": {
              "enable": true
            }
          }
        }
```

Firefox browser was used, no login in the UI.

### Expected behavior

I can login in the UI using the htpasswd file as AuthN source. Either with a form based login or a simple trigger of the native browser dialog.

### Screenshots

![image](https://github.com/project-zot/zot/assets/985728/cfc752d0-c74a-45b8-af95-ea09d14b05ea)

**Comment by andaaron** [comment]
Hi @everflux, 

With regards to the UI login. There have been some authentication bug fixes related to the UI in the last week, which are now on main (https://github.com/project-zot/zot/pull/1647 and https://github.com/project-zot/zot/pull/1662)
These are specific to the use case when local authentication is enabled together with anonymous access - which seem to be your case as well looking at the config.

**Comment by everflux** [comment]
Thanks for picking this up!
I will open a separate issue for feedback on the doc, as it seems to be appreciated.
