### ISSUE TITLE
[Bug]:  Misleading documentation in regard to authentication configuration

### ISSUE THREAD

**Issue by everflux** [project-zot/zot#1673]
### zot version

helm/website

### Describe the bug

helm chart version: 0.1.26, `helm show all project-zot/zot` provides the following output

```
# Alternatively, the configuration can include authentication and acessControl
# data and we can use mountSecret option for the passwords.
#
#  config.json: |-
#    {
#      "storage": { "rootDirectory": "/var/lib/registry" },
#      "http": { "address": "0.0.0.0", "port": "5000" },
#      "auth": { "htpasswd": { "path": "/secret/htpasswd" } },
#      "accessControl": {
#        "**": {
#          "policies": [{
#          "users": ["user"],
#            "actions": ["read"]
#          }],
#          "defaultPolicy": []
#        },
#        "adminPolicy": {
#          "users": ["admin"],
#          "actions": ["read", "create", "update", "delete"]
#        }
#      },
#      "log": { "level": "debug" }
#    }
```
This seems to be wrong as the `accessControl` and `auth` properties need to be nested inside the `http`, otherwise zot crashes on start with an unknown property error.

On the website https://zotregistry.io/v1.4.3/articles/authn-authz/#example-access-control-configuration the `accessControl` example reads
```
"http": {
...
  "accessControl": {
    "**": {
```
leading to an unknown property error as well, it seems that the key `repositories` is missing before specifying repository specific access rules.

At https://zotregistry.io/v1.4.3/admin-guide/admin-configuration/#network-configuration the list of possible attributes does not contain `accessControl`,  `auth` or `realm`.

### To reproduce

1. Configuration
2. Client tool used
3. Seen error

**Comment by rchincha** [comment]
@everflux 1.26 helm chart releases the 2.0.0-rc* releases. There is not an official release for 2.0.0 yet (imminent though!)

Best to look up examples here: https://github.com/project-zot/zot or unpublished docs at: https://github.com/project-zot/project-zot.github.io/tree/main/docs

**Comment by everflux** [comment]
Thanks for pointing out the option to get more recent documentation - perhaps this could be linked or selected on the website as well? (I like in particular how traefik https://doc.traefik.io/traefik/ and nest https://docs.nestjs.com/ do it on the lower left)

It might be a good idea to label the unofficial releases "-alpha" or something, since "-rc" implies a "release candidate" which is in my experience just a 'git tag' apart from beeing released. 
Despite that the helm chart documentation should be consistent with the targeted release, and even ignoring that the helm chart output is not consistent with the website neither.
Perhaps there is an opportunity to consider generating the same documentation for website and helm chart from the same source.

**Comment by andaaron** [comment]
Hi @everflux, the example in the helm chart has been updated updated.

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/releases/tag/v2.0.0
^ has now been released. Can we close this?

**Comment by andaaron** [comment]
Let's close this, as the docs have been updated.
