### ISSUE TITLE
[Feat]: Provide delete for admin users in the ui

### ISSUE THREAD

**Issue by everflux** [project-zot/zot#1676]
### Is your feature request related to a problem? Please describe.

I would like to be able to remove images or whole repositories through the ui.

### Describe the solution you'd like

Minimum: "delete" button (like in crane operator) for an image-tag, better: select boxes for image-tags for multi-delete, really nice to be able to remove a whole repo (f.e. after a typo.)

### Describe alternatives you've considered

CLI/API, but not as user friendly (and not sure this is in place).

**Comment by rchincha** [comment]
@everflux This has been an ask from others also.
https://github.com/project-zot/zui/issues/364

The UI is a new feature and mostly designed to be a view-only interface. But we are working on enhancing it for select mutation operations.

**Comment by peusebiu** [comment]
fixed in https://github.com/project-zot/zui/commit/c375c0697a4a64d8fce93b509aad82d008cd17e0
