### ISSUE TITLE
[Feat]:  dedupe and rebuild zot cache while starting zot

### ISSUE THREAD

**Issue by shimish2** [project-zot/zot#1732]
### Describe the solution you'd like

Currently, zot has cache and dedupe functionality but it is available when a new image is uploaded to zot. If we are starting a zot on the existing oci layout there should be a way to rebuild the cache and dedupe the oci layout.

**Comment by peusebiu** [comment]
Hi @shimish2 we already have this one: https://github.com/project-zot/zot/commit/f35ff5314698f7cbd6fd7980513bf81fec50de34

for local storage: 
1) it dedupes blobs at startup (if dedupe is enabled)
2) if dedupe is false then nothing is done

for s3 storage(where links are not supported, dedupe works by putting empty files for deduped blobs and preserves the content for one blob - original blob):
1) same as local
2) restore blobs to their initial state (takes content from original blob and copies it into deduped blobs)

This is running only at startup and in the case of s3 it can interfere with clients while it's running.

**Comment by andaaron** [comment]
See https://github.com/project-zot/zot/issues/565

**Comment by peusebiu** [comment]
unfortunately no, for local storage there is no problem, because we use hard links, but for s3, yeah, clients will get errors until it finishes.

I guess we can update this to wait for the task to finish, but we need to also update the task scheduler, I think.

**Comment by andaaron** [comment]
@shimish2 are you OK with closing this issue, or do we still need to track some changes here?
