### ISSUE TITLE
[Bug]:  `last` query parameter in `/v2/<name>/tags/list` API not working as expected

### ISSUE THREAD

**Issue by qweeah** [project-zot/zot#1771]
### zot version

v2.0.0-rc6

### Describe the bug

I am testing on [ghcr.io/project-zot/zot-linux-amd64:v2.0.0-rc6](http://ghcr.io/project-zot/zot-linux-amd64:v2.0.0-rc6)  running under localhost:7000 and seems the last query parameter doesn't working as expected
I have tags `test1`, `test2` , `test3` in my repo `test` and I sent a request to API `/v2/<name>/tags/list`, the `last` query seems not working:

- `http://localhost:7000/v2/test/tags/list?last=test1` got result `test3, test1, test2`
- `http://localhost:7000/v2/test/tags/list?last=test2` got result `test3, test1, test2`
- `http://localhost:7000/v2/test/tags/list?last=test3` got result `test3, test1, test2`

### To reproduce

1. Configuration
> docker run -dp 7000:5000 -u $(id -u $(whoami)) ghcr.io/project-zot/zot-linux-amd64:v2.0.0-rc6
3. Client tool used
I used [oras](https://github.com/oras-project/oras) v1.1.0 with below commands and output
```console
➜  ~ oras repo tags localhost:7000/test --last test1
test1
test3
test2
➜  ~ oras repo tags localhost:7000/test --last test2
test1
test3
test2
➜  ~ oras repo tags localhost:7000/test --last test3
test1
test3
test2
```

### Expected behavior

- `http://localhost:7000/v2/test/tags/list?last=test1` got result `test2, test3`
- `http://localhost:7000/v2/test/tags/list?last=test2` got result `test3`
- `http://localhost:7000/v2/test/tags/list?last=test3` got empty array result 

### Screenshots

Below are the logs from zot:
```json
{"level":"info","module":"http","username":"hello","clientIP":"172.17.0.1:50092","method":"GET","path":"/v2/test/tags/list?last=test1","statusCode":200,"latency":"0s","bodySize":48,"headers":{"Accept-Encoding":["gzip"],"Authorization":["******"],"User-Agent":["oras/1.1.0"]},"goroutine":88,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-09-07T02:19:40.91893386Z","message":"HTTP API"}

{"level":"info","module":"http","username":"hello","clientIP":"172.17.0.1:55542","method":"GET","path":"/v2/test/tags/list?last=test2","statusCode":200,"latency":"0s","bodySize":48,"headers":{"Accept-Encoding":["gzip"],"Authorization":["******"],"User-Agent":["oras/1.1.0"]},"goroutine":90,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-09-07T02:19:59.021942551Z","message":"HTTP API"}

{"level":"info","module":"http","username":"hello","clientIP":"172.17.0.1:54944","method":"GET","path":"/v2/test/tags/list?last=test3","statusCode":200,"latency":"0s","bodySize":48,"headers":{"Accept-Encoding":["gzip"],"Authorization":["******"],"User-Agent":["oras/1.1.0"]},"goroutine":93,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-09-07T02:20:02.305560322Z","message":"HTTP API"}

```

### Additional context

According to https://github.com/opencontainers/distribution-spec/blob/main/spec.md#listing-tags, the tag name specified by `last` query will not be included in the results.

**Comment by rchincha** [comment]
https://github.com/opencontainers/distribution-spec/pull/464
^ fyi

**Comment by andaaron** [comment]
I'm currently working on a fix for this issue.

**Comment by rchincha** [comment]
Thanks @qweeah for filing the issue. This was a good catch!

**Comment by andaaron** [comment]
Hi @qweeah, I merged the fix on top of main branch.
