### ISSUE TITLE
[Bug]: Delete repo:tag causes all manifests to be deleted

### ISSUE THREAD

**Issue by erikschul** [project-zot/zot#1772]
### zot version

v2.0.0-rc6

### Describe the bug

Maybe I've misunderstood how it's supposed to work.

```
#Add myapp:tag1
skopeo copy \
    --src-daemon-host unix:///Users/user/.docker/run/docker.sock \
    --dest-creds myuser:mypass \
    docker-daemon:myapp:latest docker://localhost/myapp:tag1

#Add myapp:tag2 (same blobs)
skopeo copy \
    --src-daemon-host unix:///Users/user/.docker/run/docker.sock \
    --dest-creds myuser:mypass \
    docker-daemon:myapp:latest docker://localhost/myapp:tag2

#Delete myapp:tag1
skopeo delete \
    --creds myuser:mypass \
    docker://localhost/myapp:tag1
```

I now expect that tag2 still exists.
But `index.json` has no manifests:
```
{"schemaVersion":2,"manifests":null}
```

and the blobs are garbage collected.

**Comment by rchincha** [comment]
https://github.com/containers/skopeo/blob/main/docs/skopeo-delete.1.md

`
WARNING: If image-name contains a tag (but not a digest), in the current version of Skopeo this resolves the tag into a digest, and then deletes the manifest by digest, as described above (possibly deleting all tags pointing to that manifest, not just the provided tag). This behavior may change in the future.
`
