### ISSUE TITLE
[Refactor] Sync should check features supported by upstream registry before syncing references

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#1801]
At the moment the sync logic tries to pull references without knowing if the upstream registry supports the referrers API or the oras API.
This results in a lot of calls returning responses with bad status codes, which could be avoided (for various reasons, such as spamming the log messages, hitting rate limits, slowing down zot, and so on).

At a bare minimum we can try making the referrers/oras API call once per registry (or repo?).

**Comment by rchincha** [comment]
Yes, this one is important.

**Comment by rchincha** [comment]
Can we close this?

**Comment by andaaron** [comment]
Let's close it.
