### ISSUE TITLE
There are too many and complex cicd tools for documents. Is there any integrated tool that can support callbacks for github and gitea, and promote packaging tools to be packaged into images?

### ISSUE THREAD

**Issue by mmm8955405** [project-zot/zot#1813]
### Is your feature request related to a problem? Please describe.

Supports code hosting platforms similar to Gitea and Github

**Comment by rchincha** [comment]
@mmm8955405 is this zot-specific question? or a more general one? If the latter, best to move it under "Discussions"

**Comment by rchincha** [comment]
@mmm8955405 closing this issue, pls re-open if you a zot-specific question.
