### ISSUE TITLE
[Refactor][Investigate]: MetaDB: Use protobuf for data encoding instead of json

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#1831]
Currently we use jsons, and marshal/unmarshal is very time consuming and if the data set is very large, zot performance decreases.

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/pull/1829

Some working and non-working pseudocode ...

**Comment by rchincha** [comment]
First step is to remove unnecessary unmarshals.
Second step is PR #1829
