### ISSUE TITLE
[Clean Code]: add type aliases instead of plain 'string' types

### ISSUE THREAD

**Issue by laurentiuNiculae** [project-zot/zot#1838]
### Is your feature request related to a problem? Please describe.

When reading the code and especially the type declarations in meta/types it's quite difficult to follow the logic for example:
```go 
type RepoMetadata struct {
	Name string
	Tags map[string]Descriptor

	Statistics map[string]DescriptorStatistics
        ...
}
```
It's not trivial to understand what the `string` for `Tags map[string]Descriptor` or `Statistics map[string]DescriptorStatistics` refers to.

### Describe the solution you'd like

We can use this Go feature to declare a type alias:
```go
type RepoName       = string
type ManifestDifest = string
```

> [!IMPORTANT]  
> To not be confused with the type declaration:  
> ```go 
> type RepoName string
> ```

This solution comes with 0 cost, it's just a code documentation feature.

**Comment by andaaron** [comment]
Fixed in #2043
