### ISSUE TITLE
[Feat]: ui/vulnerabilities - allow export of vuln list

### ISSUE THREAD

**Issue by mikemccracken** [project-zot/zot#1999]
### Is your feature request related to a problem? Please describe.

sometimes a list is large and I need to coordinate evaluating it with others and track status and conclusions.

other platforms allow exporting results as .xls, which lets us build a shared spreadsheet to track such work.

This is a useful feature that can be a shortcut around implementing a lot of security review workflow feature requests directly in the zot ui

**Comment by mikemccracken** [comment]
IMO this one is critical for enabling comparison of results between zot and existing scan tools

**Comment by andaaron** [comment]
Done in https://github.com/project-zot/zui/pull/404
