### ISSUE TITLE
[Feat]: ui/vulnerabilities: allow filtering out results / more complicated queries

### ISSUE THREAD

**Issue by mikemccracken** [project-zot/zot#2000]
### Is your feature request related to a problem? Please describe.

if I am evaluating a large list of results, I might like to be able to see how many vulnerabilities do *not* match e.g. "golang", in order to get a better idea of what's left after I update one particularly noisy component.

### Describe the solution you'd like

let me do negative searches

### Describe alternatives you've considered

another alternative is to just export as described in https://github.com/project-zot/zot/issues/1999
then I can just filter things out in excel like the Old I am

**Comment by andaaron** [comment]
Backend done in: https://github.com/project-zot/zot/pull/2163
Frontend in progress at: https://github.com/project-zot/zui/pull/415
