### ISSUE TITLE
[Question]: distSpecVersion in docs

### ISSUE THREAD

**Issue by rlex** [project-zot/zot#2143]
### zot version

v2.0.0

### Describe the bug

Not quite a bug, but i noticed that samples in repo with configs have 
```
    "distSpecVersion": "1.1.0-dev",
```

ie 

https://github.com/project-zot/zot/blob/main/examples/config-all-remote.json

Is that reference to OCI spec? Or some internal zot one?
What should i use in live install?

### To reproduce

N/A

**Comment by rchincha** [comment]
@rlex thanks for trying out `zot`.

`zot` follows the OCI distribution spec closely and that is merely information we track to indicate which version is being supported in this config and binary.

https://github.com/opencontainers/distribution-spec/blob/main/spec.md
https://github.com/opencontainers/distribution-spec/blob/v1.1.0-rc3/spec.md

**Comment by rlex** [comment]
So what should be default for 2.0.0? I created ansible role for installing zot and it have basic config (mirror mode): 
https://github.com/rlex/ansible-role-zot

I'm currently using 1.1.0-dev

**Comment by rchincha** [comment]
> What should i use in live install?
> I'm currently using 1.1.0-dev

^ this is correct.

https://github.com/project-zot/zot/tree/v2.0.0/examples
^ these are validated as part of our CI.

Before deploying, you can always do this first.
https://zotregistry.io/v2.0.0/admin-guide/admin-configuration/#verifying-the-configuration-file

**Comment by rlex** [comment]
> Before deploying, you can always do this first.
> https://zotregistry.io/v2.0.0/admin-guide/admin-configuration/#verifying-the-configuration-file

This for some reason doesn't work with ansible-provided validation (will investigate it a bit later).

Thanks for info!

**Comment by rchincha** [comment]
Nothing further actionable. Closing this issue.
