### ISSUE TITLE
implement "scrub" to check manifest/blob integrity

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#215]
This a server-side functionality to aid site admins.
We run the service as follows:
`zot serve config.json`

In case of suspected corrupted blobs, we should be able to do:
`zot scrub config.json`

Since we use oci image layout, we should look at importing/using umoci codebase [1] as a library. We already use it for GC etc.

Additionally,

Deletion of blobs due to dist-spec and separately, our GC support can affect integrity of manifests/blobs.
Run a periodic or on-demand data integrity checker [2] to catch any problems early.

References:

[1] https://github.com/opencontainers/umoci
[2] https://docs.oracle.com/cd/E23823_01/html/819-5461/gbbwa.html

**Comment by andaaron** [comment]
Talked with @rchincha about this.
For now let's find all dirs with an index.json recursively and basically and run "umoci stat" (or equivalent from library) for every OCI layout.

**Comment by rchincha** [comment]
The idea is to "scrub" the images in order to catch any issues on-demand/early.
Has a precedent [1]

References:
[1] https://docs.oracle.com/cd/E18752_01/html/819-5461/gbbwa.html

**Comment by andaaron** [comment]
This has been fixed
