### ISSUE TITLE
zotregistry.io: NXDOMAIN

### ISSUE THREAD

**Issue by otaconix** [project-zot/zot#2157]
### zot version

n/a

### Describe the bug

There doesn't seem to be any DNS records for zotregistry.io.

In case anyone else looks for a place to read the rendered docs, I found https://chofnar.github.io/project-zot.github.io/docs/.

### To reproduce

```
dig @9.9.9.9 zotregistry.io
```

### Expected behavior

Existing DNS records for the domain.

**Comment by smarticu5** [comment]
Commenting to say I'm seeing the same. No DNS records available.

**Comment by rchincha** [comment]
Hi All, we are affected by this:
https://support.google.com/domains/answer/13689670?hl=en

We are aware of this issue and working to resolve it asap.

**Comment by rchincha** [comment]
For latest documentation, pls see
https://github.com/project-zot/project-zot.github.io/tree/gh-pages/v2.0.0

**Comment by rchincha** [comment]
https://zotregistry.dev/

If using helm,
helm repo add zot https://zotregistry.dev/helm-charts/

Between Google domains sale to Squarespace, renewal notice sent out during holidays, etc, [zotregistry.io](http://zotregistry.io/) has been parked. We are trying to revive it, however, going forward would move to https://zotregistry.dev/ - we have put in better control/process around this. Our sincerest apologies for this disruption 😞

**Comment by rchincha** [comment]
Closing this issue, since it is "resolved".
