### ISSUE TITLE
[Feat]: Publish zot multi-arch images

### ISSUE THREAD

**Issue by sagikazarmark** [project-zot/zot#2190]
### Is your feature request related to a problem? Please describe.

Having to add the target OS and arch to the image name is extremely annoying. Deployment instructions and assets (eg. `docker-compose.yaml` or Kubernetes YAMLs) become much less portable.

### Describe the solution you'd like

Publish multi-arch zot images (in addition to the existing ones)

### Describe alternatives you've considered

I've been building custom images so far, but I'd like to stop doing that.

### Additional context

I know it's been discussed a few times (forgive my ignorance, I only found #1761, I stopped searching for other occurrences after 10 minutes), but other than "conservative choice" I haven't seen an explanation what the harm is in providing a multi-arch image in addition to the existing ones.

Is there a technical difficulty that makes producing such images hard/impossible?

**Comment by rchincha** [comment]
@sagikazarmark yes, this has come up a few times.

Blockers:
1. We want to publish OCI images only
2. Currently we use https://github.com/project-stacker/stacker to do so.
3. `stacker` lacks the ability to publish a multi-arch image index

Let us know of alternatives and we can definitely evaluate.

**Comment by sagikazarmark** [comment]
I believe there are tools out there that can take single-arch images and create multi-arch images. Buildah comes to mind: https://github.com/containers/buildah

As a temporary solution you could take the images from stacker and feed them into `buildah manifest` to publish multi-arch images.

There might be other tools out there as well.

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/pull/2214

**Comment by jkroepke** [comment]
[docker buildx imagetools create](https://docs.docker.com/engine/reference/commandline/buildx_imagetools_create/) works great, too.
