### ISSUE TITLE
[Bug]: Typos in website directions for auth? 

### ISSUE THREAD

**Issue by cboettig** [project-zot/zot#2191]
### zot version

2.0.1

### Describe the bug

Thanks for an amazing project, really fantastic job.  Just reporting a small issue in docs.  

The URL, https://zotregistry.dev/v2.0.1/articles/authn-authz/#using-google-github-or-gitlab, describes OAuth based authentication with providers including GitHub, but appears to incorrectly state the callback URL, as, e.g.

```
http://zot.example.com:8080/auth/callback/github
```

Contrast this to the README in https://github.com/project-zot/zot/blob/9def35f3b8b38f5a438146a09087edcec00537c7/examples/README.md?plain=1#L294 which shows an additional `zot/` in the path before `auth`.  Testing with the current (2.0.1) release I can confirm this extra bit is necessary.

Note also that going to the docs page without the version in the URL, https://zotregistry.dev/articles/authn-authz/#using-google-github-or-gitlab, we no longer have these instructions at all :(.  

 

### To reproduce

See URLs above

**Comment by rchincha** [comment]
@cboettig do you want to give us a PR? We strongly encourage community participation.

**Comment by cboettig** [comment]
@rchincha that's awesome, thanks for the link! I've taken a stab at this in https://github.com/project-zot/project-zot.github.io/pull/153.  Hopefully I've edited the correct source and didn't mess things up, but critique away, I'm here to learn.
