### ISSUE TITLE
[Feat]: support habor-like "cache check on pull" in registry mirroring

### ISSUE THREAD

**Issue by networkhermit** [project-zot/zot#2284]
### Is your feature request related to a problem? Please describe.

In my understanding registry mirroring with zot currently have a few shortcomings:

1. Use on-demand synchronization alone could cause stale cache/outdated image.
2. Periodically polling from the upstream registry could easily hit rate limits, and I think there is no need to poll rarely pulled images.

P.S.

I am currently evaluating zot as a alternative to harbor proxy cache, but I don't know how many images in my cluster are still in docker image format (some deployments use sha256 tag). Is there any recommended method to quickly check the image format?

### Describe the solution you'd like

Quoted from [How Harbor proxy cache works](https://goharbor.io/docs/2.10.0/administration/configure-proxy-cache/)

> When a pull request comes to a proxy cache project, if the image is not cached, Harbor pulls the image from the target registry and serves the pull command as if it is a local image from the proxy cache project. The proxy cache project then caches the image for a future request.
>
> The next time a user requests that image, Harbor checks the image’s latest manifest in the target registry and serves the image based on the following scenarios:
>
> If the image has not been updated in the target registry, the cached image is served from the proxy cache project.
>
> If the image has been updated in the target registry, the new image is pulled from the target registry, then served and cached in the proxy cache project.
>
> If the target registry is not reachable, the proxy cache project serves the cached image.
>
> If the image is no longer in the target registry, no image is served.
> 
> As of Harbor v2.1.1, Harbor proxy cache fires a HEAD request to determine whether any layer of a cached image has been updated in the Docker Hub registry. Using this method to check the target registry will not trigger the [Docker Hub rate limiter](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/). If any image layer was updated, the proxy cache will pull the new image, which will count towards the Docker Hub rate limiter.

I think that mechanism is deserve the effort.

**Comment by peusebiu** [comment]
Hello @networkhermit 

Zot's sync works in a similar way, there are s ome differences though.

Thanks for trying out zot!
> > When a pull request comes to a proxy cache project, if the image is not cached, Harbor pulls the image from the target registry and serves the pull command as if it is a local image from the proxy cache project. The proxy cache project then caches the image for a future request.

true for zot.

> > The next time a user requests that image, Harbor checks the image’s latest manifest in the target registry and serves the image based on the following scenarios:
> > If the image has not been updated in the target registry, the cached image is served from the proxy cache project.

true for zot.

> > If the image has been updated in the target registry, the new image is pulled from the target registry, then served and cached in the proxy cache project.

true for zot

> > If the target registry is not reachable, the proxy cache project serves the cached image.

true for zot
> > If the image is no longer in the target registry, no image is served.

false for zot, zot will continue to serve the local image, it won't remove or invalidate it.

> > As of Harbor v2.1.1, Harbor proxy cache fires a HEAD request to determine whether any layer of a cached image has been updated in the Docker Hub registry. Using this method to check the target registry will not trigger the [Docker Hub rate limiter](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/). If any image layer was updated, the proxy cache will pull the new image, which will count towards the Docker Hub rate limiter.
> 

This is not true for zot, because we are converting docker images to OCI and we don't store the mapping between Docker digests and OCI digests so that we can compare later.

Because of this conversion, to check if a docker image is already cached, we first get the manifest, then its config blob and convert them to OCI, which will give us the manifest digest, then it will check the cache for that OCI manifest digest and if's the same with the local one then zot will serve the cached image, otherwise it will first pull the update from target then serve it.

I think harbor stores the docker images as they are, I don't think harbor converts them to OCI, right?

**Comment by rchincha** [comment]
> I'm curious that if the original image is converted to OCI format when mirroring, would there be some kind of label in the web ui?

Hi @networkhermit,

**All** images in zot are OCI only (either natively or converted). Not sure how a label would help here.

Also, we would be remiss if we didn't mention https://github.com/project-zot/zot/issues/724

**Comment by networkhermit** [comment]
> All images in zot are OCI only (either natively or converted). Not sure how a label would help here.

I think it is helpful to explicit label image is "Converted", meaning the image signature / metadata could be different from the upstream image.

**Comment by rchincha** [comment]
@networkhermit "add a label" as in an annotation? to the image after conversion. Ideally, we don't want to mutate the image anymore than we already are.

**Comment by networkhermit** [comment]
> @networkhermit "add a label" as in an annotation? to the image after conversion. Ideally, we don't want to mutate the image anymore than we already are.

No. Not label/annotation in the image manifest, but metadata attribute or tag stored only in zot, so it can be displayed in the web interface. But I prefer to disable the image convertion altogether to avoid signature/checksum mismatch.

**Comment by rchincha** [comment]
> But I prefer to disable the image conversion altogether to avoid signature/checksum mismatch.
In short-term, yes, https://github.com/project-zot/zot/issues/724

In long-term, if under your control of course, would suggest publishing OCI images directly upstream (dockerhub in this case?)

**Comment by rchincha** [comment]
v2.1.2-rc3 and above now supports docker images natively.
sync/mirror is a little complicated to deal with. zot being a OCI registry first and foremost, if upstream is docker image, what do we do downstream? preserve or convert or both etc

**Comment by networkhermit** [comment]
I think adding an option to preserve the upstream format is necessary, or even make it the default behavior.

Personally, I use `skopeo copy --all --preserve-digests` to preserve the upstream digests and all the images in the list. Although, Harbor Registry doesn't seem to copy all the images with different OS and architecture.
