### ISSUE TITLE
[Bug]: When pushing an image while being unauthorized, the image metadata is created in the catalog

### ISSUE THREAD

**Issue by allanger** [project-zot/zot#2392]
### zot version

v2.0.3

### Describe the bug

Our zot is configured to accept only `read` requests from unauthorized users. We've tested whether images can make to the registry when being pushed by unauthorized users. 

We've tried using docker/nerdctl/podman. And it seems like image layers are not uploaded, but image metadata is getting to zot when using `nerdctl` and `docker`

So if I push an image using `docker` or `nerdctl` I can find a name of the image in the `catalog`, and when pushing with `podman`, images seem not to appear. 

### To reproduce

1. Configuration
```json
    {
        "storage":
        {
            "rootDirectory": "/var/lib/registry",
            "dedupe": true,
            "gc": true,
            "gcDelay": "1h",
            "gcInterval": "24h"
        },
        "http":
        {
            "auth": 
            {
                "htpasswd": 
                {
                  "path": "/secret/htpasswd"
                }
            },
            "accessControl": 
            {
                "metrics":
                {
                  "users": ["prom"]
                },
                "repositories": 
                {
                  "**": 
                  {
                      "anonymousPolicy": ["read"],
                      "policies": 
                      [
                          {
                              "users": ["admin"],
                              "actions": 
                              [
                                  "read",
                                  "create",
                                  "update",
                                  "delete"
                              ]
                          }
                      ]
                  }
                }
            },
            "address": "0.0.0.0",
            "port": "5000"
        },
        "log":
        {
            "level": "debug"
        },
        "extensions": {
          "scrub": {
            "enable": true
          },
          "search": {
            "enable": true,
            "cve": {
                "updateInterval": "2h"
            }
          },
          "metrics": {
            "enable": true,
            "prometheus": {
                "path": "/metrics"
            }
          }
        }
    }
```

2. Client tool used

- podman
- nerdctl
- docker
3. Seen error

New `repository/image` appears when browsing through the `/v2/_catalog`, but it seems to be nothing more than metadata

### Expected behavior

I would expect not to see an image name in the catalog, if I wasn't allowed to push it

**Comment by rchincha** [comment]
@allanger just trying to figure out if docker/nerdctl somehow pushing with creds behind the scenes.
Also, best practices for authZ policy would be to set a adminPolicy, defaultPolicy, anonymousPolicy and then the per-user overrides.

**Comment by allanger** [comment]
> Also, best practices for authZ policy would be to set a adminPolicy, defaultPolicy, anonymousPolicy and then the per-user overrides.

Yep, sure. But the thing is that we don't need users, because we're using the registry as a cache. (I've removed that part from the config because I thought it's irrelevant, I hope it is) 

We only need to have anonymous read and that's it. Admin exists just in case

> Hi @allanger can you please provide the zot logs produced when pushing an image using nerdctl/docker?

I'll send logs tomorrow.

**Comment by allanger** [comment]
It turned out not to be related to `podman/nerdctl`. And I can't even reproduce it in 100% of cases.

It seems like if you push an image that is already in zot, but using another tag, there is a chance that it's going to add a new metadata, to registry. 

But now I can't reproduce it again, and no image appears. I think that it might be related to our configuration, so I guess I'll close this issue. 

If I'm able to find a way to reproduce it again, I'll re-open it with more details.

Regarding logs, I cant find anything strange there too, it's just a mix of `404` when blobs are not found and then `401` when client tries to upload a blob. So it seems alright. I can still attach it though, if you'd like

**Comment by andaaron** [comment]
@allanger I was asking about log messages since the username and Authorization headers are shown for requests if included by the client.

**Comment by andaaron** [comment]
It doesn't look like the client is sending credentials. I'm still wondering why is some cases these calls would go though.
