### ISSUE TITLE
[Bug]: Image index pulled from other registry are modified

### ISSUE THREAD

**Issue by AlbanBedel** [project-zot/zot#2417]
### zot version

v2.0.4

### Describe the bug

When zot is configured as pull through cache with an upstream registry and one try to get an image index the returned version is sometimes different from the upstream one resulting in a different digest. I first noticed that because the `artifactType` attribute was missing from my index, but fields are also re-ordered, white spaces are not preserved, etc.

### To reproduce

1. Setup zot as pull through cache to an upstream registry
2. Push an image index with `artifactType` set and a non standard field order to the upstream registry:
```
echo '{"schemaVersion": 2, "manifests": [],    "mediaType": "application/vnd.oci.image.index.v1+json","artifactType": "application/vnd.test.index.v1+json"}' | oras manifest push upstream-registry.example.com/test/my-index:v1 -
```
3. Pull the image through zot:
```
skopeo inspect --raw --tls-verify=false docker://localhost:8000/test/my-index:v1 | jq
```
4. Notice that the returned document miss the `artifactType` field, re-ordered the fields and stripped the additional white spaces.

### Expected behavior

The index blob returned by zot is identical to the upstream one.

### Additional context

I first noticed this because my index point to large images and each `skopeo inspect` would trigger a full re-download because the local digest doesn't match with the upstream one. So it also seems that already present blobs are ignored when re-syncing the image, but I have not fully checked this.

Pushing the index directly to zot works fine so the issue has to do with the sync process.

**Comment by rchincha** [comment]
@AlbanBedel trying to reproduce this issue

**Comment by rchincha** [comment]
@AlbanBedel is the upstream image a docker image. Note that `zot` is a OCI-only registry which means all images once they land in `zot` must be OCI format, which may mean some images are converted.

**Comment by AlbanBedel** [comment]
As you can see in the reproduction test the media type is `application/vnd.oci.image.index.v1+json` which is an OCI type.

**Comment by AlbanBedel** [comment]
I have tracked down the issue to a bug in the containers/image module: https://github.com/containers/image/issues/2460
