### ISSUE TITLE
[Bug]: Listing image in UI fails with DynamoDB and multiple tags for the same digest

### ISSUE THREAD

**Issue by fabianmp** [project-zot/zot#2464]
### zot version

v2.0.4

### Describe the bug

If multiple tags refer to the same digest, trying to view the image details in the UI fails and redirects back to the image overview.
The log contains the message `"error":"operation error DynamoDB: BatchGetItem` and `ValidationException: Provided list of item keys contains duplicates`.

### To reproduce

1. Configure zot to use DynamoDB as remote cache
2. Push an image and create a second tag for the same digest
3. Try to view image details in UI
4. User is redirected to image list instead of detail view

### Expected behavior

Image details are shown in the UI even if multiple tags refer to the same digest

**Comment by rchincha** [comment]
@fabianmp thanks for trying out zot. We will look at this.
