### ISSUE TITLE
[Feat]: Upgrade go dependencies to newest majors

### ISSUE THREAD

**Issue by AndersBennedsgaard** [project-zot/zot#2522]
### Is your feature request related to a problem? Please describe.

I noticed that Zot use `github.com/zitadel/oidc` v1.13.5, when the newest version is v3.25.1:

https://github.com/project-zot/zot/blob/002ff05f6e5ab3870aca75e616e8a4ed9b4a5c68/go.mod#L63

This led me to try running [gomajor](https://github.com/icholy/gomajor) on Zot, and i found multiple dependencies that should be upgraded (using `gomajor list`):

```text
github.com/aws/aws-sdk-go: v1.54.11 [latest v1.54.13]
github.com/containers/common: v0.59.1 [latest v1.0.1]
github.com/didip/tollbooth/v6: v6.1.2 [latest v7.0.2]
github.com/google/go-github/v52: v52.0.0 [latest v62.0.0]
github.com/sigstore/sigstore: v1.8.4 [latest v1.8.6]
github.com/swaggo/http-swagger: v1.3.4 [latest v2.0.2]
github.com/zitadel/oidc: v1.13.5 [latest v3.25.1]
gopkg.in/resty.v1: v1.12.0 [latest v2.13.1]
gopkg.in/yaml.v2: v2.4.0 [latest v3.0.1]
```

Most notably, `github.com/containers/common` v1 is released, `github.com/google/go-github` has 10 new major versions, and `github.com/zitadel/oidc` v3 are released

### Describe the solution you'd like

Upgrade the dependencies

**Comment by rchincha** [comment]
@AndersBennedsgaard Some of these deps are used for test code and others not. We have started looking at the zitadel dep.

**Comment by rchincha** [comment]
@AndersBennedsgaard if you are planning to submit a PR for this, we approve and very interested.

**Comment by rchincha** [comment]
> github.com/zitadel/oidc v3 are released

^ this has been resolved

**Comment by rchincha** [comment]
gopkg.in/yaml.v2: v2.4.0 [latest v3.0.1]
^ this is done also

gopkg.in/resty.v1: v1.12.0 [latest v2.13.1]
^ this is next

**Comment by rchincha** [comment]
github.com/zitadel/oidc/v3 v3.30.1

**Comment by rchincha** [comment]
I think this issue can be closed. Keeping the pkgs updated is an ongoing chore.
