### ISSUE TITLE
Use distribution v3

### ISSUE THREAD

**Issue by jkroepke** [project-zot/zot#2525]
### Is your feature request related to a problem? Please describe.

My open PR #2223 about Azure Backend depends on v3 Distribution yet.

v3 is not mark as stable yet, but dev doesn’t recommend to use v2 anymore: 

https://github.com/distribution/distribution/issues/4382#issuecomment-2165257526
. 

### Describe the solution you'd like

Please upgrade to v3 Distribution that my PR can be merged

### Describe alternatives you've considered

-

**Comment by rchincha** [comment]
@jkroepke very interested in your PR https://github.com/project-zot/zot/pull/2223
> Let's target this for v2.1.0

^ this release train is upon us now.

But how does one separate the go.mod update from the PR, seems like a hard dependency. I would just add it as a separate commit to the same PR. I suspect resolving the go dep hell will take some work.

**Comment by jkroepke** [comment]
I hope, you have a good test coverage.
