### ISSUE TITLE
[Feat]: Add LastPullTimestamp in GraphQL ImageList

### ISSUE THREAD

**Issue by skoppe** [project-zot/zot#2595]
### Is your feature request related to a problem? Please describe.

The `LastPullTimestamp` can be used alongside the other statistics to analyze usage of tags. Right now only `LastUpdated` and `DownloadCount` are exposed.

### Describe the solution you'd like

To add the LastPullTimestamp to the GraphQL model.

**Comment by rchincha** [comment]
@skoppe we already track this info in as part of our Retention policy feature. Maybe we can just expose this.
Would be nice to know what your actual use case is though.

**Comment by skoppe** [comment]
> Would be nice to know what your actual use case is though.

Nothing planned at the moment, it just seemed valuable information that is already available, just not exposed. I figured anyone interested in `LastUpdated` and `DownloadCount` would be interested in `LastPullTimestamp` as well.

> we already track this info in as part of our Retention policy feature

I am aware, hence me suggested exposing it.

**Comment by rchincha** [comment]
@eusebiu-constantin-petu-dbk 
pls take a look at this.
