### ISSUE TITLE
[Bug]: Listing images in UI fails with DynamoDB and many repositories

### ISSUE THREAD

**Issue by fabianmp** [project-zot/zot#2627]
### zot version

v2.1.0

### Describe the bug

If there are more than 100 repositories the UI fails to list them on the start/explore page when using DynamoDB as database.
The page stays in loading state. Looking at the request it returns with status 200 but the response contains a DynamoDB error

`operation error DynamoDB: BatchGetItem, https response error StatusCode: 400, api error ValidationException: 1 validation error detected: Value '[...]' at 'requestItems.<TABLE_NAME>.member.keys' failed to satisfy constraint: Member must have length less than or equal to 100`

The issue seems to appear in https://github.com/project-zot/zot/blob/main/pkg/meta/dynamodb/dynamodb.go#L1975 where BatchGetItems only allows to retrieve up to 100 items.

### To reproduce

1. Configure zot to use DynamoDB as remote cache
2. Push more than 100 different images
3. Try to view the explore page in the UI
4. Page seems to be in loading state, search request returns with error

### Expected behavior

List of repositories is diplayed

**Comment by rchincha** [comment]
Thanks @fabianmp for reporting this.

Indeed,
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html

**Comment by rchincha** [comment]
@fabianmp 

Do you want to try this PR out to test at your end?
https://github.com/project-zot/zot/pull/2629

**Comment by fabianmp** [comment]
sure, do you have a Docker image or binary I can use?

**Comment by rchincha** [comment]
@fabianmp 

You can either checkout my branch and `make binary` and find the binary under `bin/`
`git clone -b issue-2627 https://github.com/rchincha/zot.git`

or try this image when ready
https://github.com/rchincha/zot/pkgs/container/zot-linux-amd64/269673544?tag=v2.1.1-issue-2627

**Comment by fabianmp** [comment]
I have tested the image and now I get an error "image meta not found".
Searching for repositories and viewing a specific repository still works.

**Comment by rchincha** [comment]
> I have tested the image and now I get an error "image meta not found". 

Can you share logs around this failure.

> Searching for repositories and viewing a specific repository still works.

Still works or doesn't work? If it works, sounds like it is now an improvement?

**Comment by rchincha** [comment]
@fabianmp

> I'm not a Go programmer but it looks to me as if this check should be done after the for loop on batchedResp.

Indeed! :)

PR is now updated.

Also, if you prefer,
https://github.com/rchincha/zot/pkgs/container/zot-linux-amd64/271515843?tag=v2.1.1-issue-2627-1

**Comment by fabianmp** [comment]
now I get an error
`{
    "errors": [
        {
            "message": "internal system error",
            "path": [
                "GlobalSearch"
            ]
        }
    ],
    "data": null
}`

and the backend logs `runtime error: slice bounds out of range [100:4]` in `zotregistry.dev/zot/pkg/meta/dynamodb/dynamodb.go:1989`.

I think you need to use `digests[start:start+end]` instead of `digests[start:end]` for correct slicing

**Comment by rchincha** [comment]
https://github.com/rchincha/zot/releases/tag/v2.1.1-issue-2627-2
Also, PR updated.

**Comment by fabianmp** [comment]
the latest version works, thanks for your effort! Looking forward to the next release!

**Comment by rchincha** [comment]
v2.1.2-rc1 is now released fyi.
