### ISSUE TITLE
After setting the credentials, it still cannot be used

### ISSUE THREAD

**Issue by imaxun** [project-zot/zot#2677]
### zot version

ghcr.io/project-zot/zot-linux-amd64:v2.1.1

### Describe the bug

![image](https://github.com/user-attachments/assets/4e1fc195-d3ad-4c96-9fc8-cd31f68bff1f)

### To reproduce

1. Configuration
2. Client tool used
3. Seen error

**Comment by andaaron** [comment]
Hi @imaxun, please see https://zotregistry.dev/v2.1.0/articles/mirroring. How does your zot sync configuration look like?
