### ISSUE TITLE
TestInterruptedBlobUpload fails from time to time

### ISSUE THREAD

**Issue by adodon2go** [project-zot/zot#273]
Reproduced it twice today on 10.195.70.248 (48 cores bare metal).
For login details contact me on the chat

Full logs can be found here : https://gist.github.com/adodon2go/4a3b2cbbc52398652ce364c0edc61de3

**Comment by adodon2go** [comment]
Still reproducible.

**Comment by peusebiu** [comment]
I'll look on it asap

**Comment by adodon2go** [comment]
Unable to reproduce the issue after running ~ 10 times. 
Most probably the issue was fixed after recent refactoring in the sync test code.
