### ISSUE TITLE
[Bug]: unable to start zot with dynamodb cache driver

### ISSUE THREAD

**Issue by vanhtuan0409** [project-zot/zot#2731]
### zot version

v2.1.1

### Describe the bug

Unable to start zot registry with cache driver dynamodb

### To reproduce

1. Configuration: config zot with dynamodb cache driver. Sufficient IAM permission
2. Seen error: `exceeded max wait time for TableExists waiter`

### Expected behavior

able to create dynamodb table and able to start zot registry

**Comment by vanhtuan0409** [comment]
should be fixed by https://github.com/project-zot/zot/pull/2730

**Comment by rchincha** [comment]
Fix is merged, closing this issue.
Thanks @vanhtuan0409

**Comment by keto** [comment]
I'm still getting this error on v2.1.2

**Comment by keto** [comment]
Actually, I was missing the dynamodb:DescribeTable permission. So there is couple of issues.
- Documentation does not list all required permissions.
- The error message in this case is misleading.

(Also dynamodb:Scan permission is not listed in documentation, but that is properly indicated in an error message)

**Comment by andaaron** [comment]
@keto will update the documentation.

With regards to the error message, that's not in our control, DescribeTable is called from the SDK in this specific case: https://github.com/aws/aws-sdk-go-v2/blob/service/dynamodb/v1.40.1/service/dynamodb/api_op_DescribeTable.go#L294

**Comment by andaaron** [comment]
@keto unfortunately I don't have and AWS account to test, but this should cover the needed permissions: https://github.com/project-zot/zot/pull/2963/files

"dynamodb:BatchGetItem" should also be there.
