### ISSUE TITLE
go.mod: consolidate registry access library deps

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#278]
We are currently using both https://github.com/anuvu/zot/blob/main/go.mod#L19 and https://github.com/anuvu/zot/blob/main/go.mod#L26. Can we consolidate into just one of these libraries? Would help align with "minimal" builds.

**Comment by andaaron** [comment]
No updates on this issue for a while, and the links in the issue are pointing to other packages.
It could have been related to https://github.com/project-zot/zot/pull/898.
