### ISSUE TITLE
[Bug]: Cache does not match repo

### ISSUE THREAD

**Issue by clcc2019** [project-zot/zot#2802]
### zot version

v2.1.1

### Describe the bug

{"level":"info","repository":"global/cilium","reference":"v1.16.3","goroutine":120,"caller":"zotregistry.dev/zot/pkg/api/routes.go:2023","time":"2024-11-21T09:57:57.011823158Z","message":"trying to get updated image by syncing on demand"}
{"level":"info","goroutine":122,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:508","time":"2024-11-21T09:57:57.011907572Z","message":"getting available client"}
{"level":"info","remote":"https://public-repo.hs.com","repository":"global/cilium","reference":"v1.16.3","goroutine":122,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:301","time":"2024-11-21T09:57:57.023594191Z","message":"will not sync image, filtered out by content"}
{"level":"error","error":"image is filtered out by sync config","repository":"global/cilium","reference":"v1.16.3","goroutine":120,"caller":"zotregistry.dev/zot/pkg/api/routes.go:2027","time":"2024-11-21T09:57:57.023763512Z","message":"failed to sync image"}

```shell
nerctl pull public-repo.hs.com/global/cilium:v1.16.3
```

<img width="664" alt="image" src="https://github.com/user-attachments/assets/9a535f17-91c2-4e53-ba45-9d32fb455e79">

### To reproduce

1. Configuration
2. Client tool used
3. Seen error

**Comment by clcc2019** [comment]
> @clcc2019
> 
> Did you look at the following? https://github.com/project-zot/zot/blob/main/examples/config-sync.json

Yes, I have tried multiple content configurations and still cannot match the image

**Comment by rchincha** [comment]
You have duplicate entries in that config.
Just add the "prefix": "**" and see if everything is sync'ed down.
Also make sure upstream paths, repos are correct (meaning no typos etc)

**Comment by clcc2019** [comment]
> You have duplicate entries in that config. Just add the "prefix": "**" and see if everything is sync'ed down. Also make sure upstream paths, repos are correct (meaning no typos etc)

I have tested it and found that when on-demand synchronization is enabled, you cannot use prefix to filter repo and destination.

**Comment by andaaron** [comment]
Destination is not a filter, it is a prefix added to the local zot image copy, a folder in zot storage where the local copy of the image resides. You also need to include this prefix in the url when you pull from zot.
