### ISSUE TITLE
storage: prevent tag overwrites controlled via configuration

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#283]
Once an image is uploaded with a tag, don't allow overwrites for that same tag.
Default should be to prevent the overwrites:
"allowOverwrites" set to true explicitly.

**Comment by andaaron** [comment]
Laurentiu will look into this.

**Comment by andaaron** [comment]
Suggestion:
- Let's have the `allowOverwrites` flag under `http`.
- In case of attempt to overwrite return error code `405` - Method Not Allowed.

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/pull/445

^ addresses this issue. However, do we need to make a distinction between any tag and a semver tag?
