### ISSUE TITLE
Add project logo

### ISSUE THREAD

**Issue by jdolitsky** [project-zot/zot#292]
I provide this image for inspiration:

![image](https://user-images.githubusercontent.com/393494/143055338-e3cd6826-2d06-4a23-8f20-ed9eb0ad6a76.png)

**Comment by hallyn** [comment]
I mean, the actual inspiration for the name was more like https://i.colnect.net/f/1792/497/Brugse-Zot.jpg  :)   But I concede that may not be very inspiring.

**Comment by rchamarthy** [comment]
I will take on this and engage some professionals. Any theme ideas apart from the above are welcome :)

**Comment by JasonvanBrackel** [comment]
Design contest started with 99 designs.  It's been fast-tracked to be done in 3 days.  When, I get the first set of candidate logos I'll hit you up for your opinion @rchamarthy

**Comment by JasonvanBrackel** [comment]
![Screenshot 2021-12-08 at 16-06-06 Check out the concepts designers are submitting for jvanbraL's new logo design](https://user-images.githubusercontent.com/942110/145284490-1de63bab-fa34-4eb3-8b84-bdd9548e2e14.png)

**Comment by JasonvanBrackel** [comment]
@rchamarthy @liljenstolpe Would love your feedback

**Comment by hallyn** [comment]
By my favorite artist:

![image](https://user-images.githubusercontent.com/1359441/145603506-7b636e83-f402-412d-9832-83fdd38cc70e.png)

**Comment by hallyn** [comment]
![](file:///tmp/zot-in-the-box.png)

**Comment by hallyn** [comment]
![image](https://user-images.githubusercontent.com/1359441/146433941-eb22899a-faa6-4a45-9ec8-ef0bd0360a6c.png)

**Comment by andaaron** [comment]
Another, newer, logo is currently used.
