### ISSUE TITLE
Develop Contribution Guidelines

### ISSUE THREAD

**Issue by rchamarthy** [project-zot/zot#314]
Contribution guidelines will be need to be developed and added to the repository. If there are existing guidelines, we'll make sure they're compatible with existing OSS project models.

**Comment by rchincha** [comment]
https://github.com/project-zot/zot#contributing

**Comment by rchincha** [comment]
https://zotregistry.io/v1.4.3/developer-guide/onboarding/?h=contr#contributor-guidelines
