### ISSUE TITLE
Prepare Short Description fro OSS Organization Donation

### ISSUE THREAD

**Issue by rchamarthy** [project-zot/zot#316]
Describe Zot simply for the purpose of proposing a contribution to an OSS project like the CNCF. This should include comparisons to other projects within the Cloud Native Landscape. Make sure to cover overlapping technologies at https://landscape.cncf.io

**Comment by rchincha** [comment]
Submission is now complete
https://landscape.cncf.io/card-mode?category=container-registry&grouping=category
