### ISSUE TITLE
Prepare Repository and Organization for Open Source Adoption

### ISSUE THREAD

**Issue by rchamarthy** [project-zot/zot#317]
We're going to us CNCF Sandbox as a template for this as they are a likely organization to donate Zot this issue will be used like an Epic to track the process of related issues.

The detailed information on the sandbox requirements can before on the google document below.

https://docs.google.com/document/d/1IlhqnmhSzs3aTPMkp_75JPYz6LD21aK1sNPrBNruDt0/edit

Work included for this to be considered complete will include
Create a Zot Project Website
Prepare Short Description for OSS Organization Donation
Develop Contribution Guidelines
Develop a Code of Conduct

**Comment by rchincha** [comment]
Task is complete:
https://landscape.cncf.io/card-mode?category=container-registry&grouping=category

We will take next steps for incubation stage.
