### ISSUE TITLE
Create a Zot Project Website

### ISSUE THREAD

**Issue by rchamarthy** [project-zot/zot#320]
Zot Project Website will be developed using Antora so the website will naturally flow into documentation as well. We intend to model it after sites similar to https://k3s.io with a simple design that will easily allow users to start working with Zot immediately.

We will be making sure the website also complies with CNCF Guidelines https://github.com/cncf/foundation/blob/master/website-guidelines.md

It should include

Quick Getting Started
Uses Cases
Very High Level Architecture Diagram
Slightly longer getting started
CTAs to learn more with links to
Documentation
Getting Started Videos
Tickets for this will be tracked at
https://github.com/project-zot/site-zot/projects/1

**Comment by JasonvanBrackel** [comment]
@sbaroulette-web is working on this.

**Comment by andaaron** [comment]
This is now tracked in other issues.
