### ISSUE TITLE
scrub: make scrub inline and periodic

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#376]
**Is your feature request related to a problem? Please describe.**

`zot scrub` scrubs the filesystem but as a offline tool.

**Describe the solution you'd like**

Would like the scrubbing to be continuous done to catch any filesystem errors.

**Comment by adodon2go** [comment]
Do we want also for scrub to take some delete actions in case image:tag is being detected as not valid?
I'm thinking this will be useful in the context of https://github.com/project-zot/zot/pull/374/files & https://github.com/project-zot/zot/issues/359.  Also maybe cleanup in the .uploads folder will be useful.

**Comment by andaaron** [comment]
In the first iteration scrib will be read-only. It would not try to fix the issue. We will fixing the issue separately.

**Comment by andaaron** [comment]
Done in https://github.com/project-zot/zot/pull/440
