### ISSUE TITLE
Image retention policy

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#425]
**Is your feature request related to a problem? Please describe.**
Zot may be running in a large variety of environments, some with limited storage.
We have added policies for downloading new images automatically using zot sync, but as disk usage grows we may need a way to automatically free storage space. 

**Describe the solution you'd like**
The zot configuration should include policies for removing old, unused images.
Maybe we should remove images using the following criteria:
- images with a specified name pattern older than a specified time
- images which have not been downloaded in a specified time interval

**Describe alternatives you've considered**
We could have separate scripts calling the zot API to delete old images, but we should solve this in zot if we can, without needing additional tooling.

**Additional context**

**Comment by rchincha** [comment]
1) How long should we wait
2) Per-repo policy?
3) Exemption - pin some images from being deleted?

**Comment by andaaron** [comment]
Duplicate of https://github.com/project-zot/zot/issues/1634
