### ISSUE TITLE
`distribution-spec` version named simply `Version` in zot logs

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#441]
**Describe the bug**
The first message in the zot logs includes a `Version`, which is actually the oci dist spec version, not the zot version. This can be misleading, as the actual zot version is in the `Commit` field.
The same value is names in the CLI command `zot --version` as `distribution-spec`.
I recommend renaming the field in the zot logs to `distribution-spec` as well.

**To Reproduce**
```
docker run -p 5000:5000 ghcr.io/project-zot/zot-linux-amd64:v1.3.9
{"level":"info","params":{"Version":"1.0.0-dev","GoVersion":"go1.17.5","Commit":"v1.3.9-bf21435d42e64b1b4a13539b1f2a66982574d684","BinaryType":"extended","AccessControl":null,"Storage":{"Dedupe":true,"GC":true,"Commit":false,"GCDelay":3600000000000,"RootDirectory":"/var/lib/registry","StorageDriver":null,"SubPaths":null},"HTTP":{"Address":"0.0.0.0","Port":"5000","TLS":null,"Auth":null,"RawAccessControl":null,"Realm":"","AllowReadAccess":false,"ReadOnly":false,"Ratelimit":null},"Log":{"Level":"debug","Output":"","Audit":""},"Extensions":null},"goroutine":1,"caller":"zotregistry.io/zot/pkg/api/controller.go:103","time":"2022-03-04T09:00:44.683144298Z","message":"configuration settings"}
```

**Comment by rchincha** [comment]
@laurentiuNiculae 

https://github.com/project-zot/zot/pull/458

Also do this for your next PR before you close this issue.
