### ISSUE TITLE
OCI Conformance: 405 Cross-mounting of a blob without the from argument should yield session id

### ISSUE THREAD

**Issue by jdolitsky** [project-zot/zot#442]
**Describe the bug**
Upon running distribution-spec conformance tests (built manually, changes unreleased on `main`), I receive a `405` error on the following test:

```
Cross-mounting of a blob without the from argument should yield session id
Expected
    <int>: 405
to equal
    <int>: 202
```

**To Reproduce**

```
docker build -t zot -f Dockerfile-conformance .
docker run -p 5000:5000 zot
```

```
export OCI_NAMESPACE=oci-conformance/distribution-test
export OCI_PASSWORD=762da120d6d42b47273bc8892be6ca55
export OCI_TEST_CONTENT_MANAGEMENT=1
export OCI_TEST_PUSH=1
export OCI_TEST_PULL=1
export OCI_CROSSMOUNT_NAMESPACE=oci-conformance/distribution-test2
export OCI_ROOT_URL=http://localhost:5000
export OCI_TEST_CONTENT_DISCOVERY=1
```

```
(cd distribution-spec/conformance/ && go test -c && mv conformance.test ../../)
./conformance.test
```

```
Ran 60 of 65 Specs in 0.322 seconds
FAIL! -- 59 Passed | 1 Failed | 0 Pending | 5 Skipped
```

**Expected behavior**

All tests pass

**Comment by jdolitsky** [comment]
Note: this is a failure against an unreleased version of the spec/tests (`main` branch / `dd38b7ed8a995fc2f6e730a4deae60e2c0ee92fe`)

**Comment by shimish2** [comment]
It is because if from parameter is invalid we are returning 405 https://github.com/project-zot/zot/blob/main/pkg/api/routes.go#L719

**Comment by jdolitsky** [comment]
Perhaps this is a bug in the upstream tests then?

Here is the relevant part of the spec
https://github.com/opencontainers/distribution-spec/blob/main/spec.md#mounting-a-blob-from-another-repository

**Comment by shimish2** [comment]
Yes its a bug in upstream tests and zot also (as per dist spec) :) 

Also dist spec here says upon failure return 404 https://github.com/opencontainers/distribution-spec/blob/main/spec.md#endpoints (last row)

**Comment by rchincha** [comment]
https://github.com/opencontainers/distribution-spec/blob/main/spec.md#mounting-a-blob-from-another-repository

"
Alternatively, if a registry does not support cross-repository mounting or is unable to mount the requested blob, it SHOULD return a 202. This indicates that the upload session has begun and that the client MAY proceed with the upload.
"

**Comment by rchincha** [comment]
@jdolitsky is this a new validation that is being added?

**Comment by jdolitsky** [comment]
appears to be introduced in https://github.com/opencontainers/distribution-spec/pull/296
