### ISSUE TITLE
report a nicer failure on a non-OCI compliant `docker push`

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#534]
**Is your feature request related to a problem? Please describe.**

Given that `zot` is a container image registry, an expectation may be that `zot` supports docker protocol and manifests. However, `zot` is a OCI-only registry and it would be nice to return a more graceful error to indicate why for example `docker push` doesn't work.

Originally reported by @SteveLasker

**Describe the solution you'd like**
`
"[Steve Lasker]:
just a suggestion you might want to put that in the docs and samples. Maybe even throw an unsupported exception when you see the docker manifest on push. 
`

It would be nice to return a more graceful error to indicate why for example `docker push` doesn't work.

**Describe alternatives you've considered**

**Additional context**

**Comment by rchincha** [comment]
Bring up zot and then try to do a `docker push` against it.

`docker push` assumes docker registry which is not oci dist-spec compliant for push. But this could be true for any non-oci compliant client. What we want to fix is that we return an error reporting the non-compliance.

**Comment by andaaron** [comment]
This looks like a client side error? Can someone confirm this `expected integer` error is not coming from zot?

**Comment by bogdanbiv** [comment]
indeed it is
