### ISSUE TITLE
image-level lint: enforce some sane image upload guidelines

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#536]
**Is your feature request related to a problem? Please describe.**

As a registry, it is possible to limit what types of images and tags get pushed into zot.
1. push/keep only signed images
2. push only images with "mandatory" annotations

**Describe the solution you'd like**
{
...
"lint": {
"onlySignedImages": true,
"mandatoryAnnotations": true,
}

**Describe alternatives you've considered**

**Additional context**

**Comment by andaaron** [comment]
@aokirisaki please look into point 2.
