### ISSUE TITLE
remove `allowReadAccess` and `ReadOnly` as they can now be controlled via access control policy

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#537]
**Describe the bug**
`allowReadAccess` and `ReadOnly` were added until access control policy feature could be added, which we now have.
So should be deprecated.

**Comment by andaaron** [comment]
> and then you want to hide a specific repo from unauthorized users (using authz config) it will not work, all the logic regarding longest matched pattern we use there will be bypased.

Can you elaborate how this works?
Sounds like a bug to be.
