### ISSUE TITLE
durable attributes: image-level attributes need to be durable

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#538]
**Is your feature request related to a problem? Please describe.**

In UI, it is useful to show image-level attributes such as "how many times downloaded", "CVEs affected", etc

Note that we cannot store these in manifest annotations since it could affect image signatures.

**Describe the solution you'd like**

Store these in a separate db. We have one for other things anyways.

**Describe alternatives you've considered**

**Additional context**

**Comment by andaaron** [comment]
Let's cover the user level attributes as part of https://github.com/project-zot/zot/issues/592

**Comment by andaaron** [comment]
In review: https://github.com/project-zot/zot/pull/979/commits
