### ISSUE TITLE
zli: currently only a subset of the graphQL queries are supported

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#547]
**Is your feature request related to a problem? Please describe.**

Our graphQL backend now supports more queries. Enhance `zli` to support all of them.

**Comment by andaaron** [comment]
Let's schedule this after https://github.com/project-zot/zot/pull/457 is done.

**Comment by andaaron** [comment]
Need to review existing graphql methods/use-cases and check which of them are not supported in ZLI.

**Comment by andaaron** [comment]
Added new subcommands for search by query and referrers API.
