### ISSUE TITLE
ci/cd: test only affected changes

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#558]
**Is your feature request related to a problem? Please describe.**

Our ci/cd pipeline is taking 30-40 mins to complete. 

**Describe the solution you'd like**

We want to achieve something similar to:
https://pypi.org/project/pytest-testmon/

We should be able to achieve this with golang tags.

Also this: https://onsi.github.io/ginkgo/#focused-specs. But this means refactor goconvey to ginkgo.

**Comment by andaaron** [comment]
CI has been improved by reorganizing the makefile and jobs, let's close this for now.
