### ISSUE TITLE
storage: root directory directly on cloud storage

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#564]
**Is your feature request related to a problem? Please describe.**

If we want to support a stateless zot (helps for clustering) but also support dedupe, then we cannot have anything on instance-local private storage. Even the dedupe cache should be on shared cloud storage.

- [x] #667 
- [ ] #953

**Comment by rchincha** [comment]
This need investigation/evaluation first.

**Comment by rchincha** [comment]
@chofnar Pls. take @peusebiu's help since he is the feature owner of this area.

**Comment by chofnar** [comment]
- [ ] #667 
- [ ] https://github.com/chofnar/zot/pull/18

**Comment by andaaron** [comment]
In review.
