### ISSUE TITLE
Testing needed for anonymous cross origin blob mount location header

### ISSUE THREAD

**Issue by sudo-bmitch** [project-zot/zot#575]
**Is your feature request related to a problem? Please describe.**
Much to my shame, I added a change without a test case in #574

**Describe the solution you'd like**
Someone that understands the testing library better than me could add a short test case to ensure the returned Location header matches a desired value.

**Describe alternatives you've considered**
None, how could there be an alternative to Zot.

**Additional context**
Hopefully #574 and #573 explain it well enough. Happy to answer any other questions.

**Comment by shimish2** [comment]
Closing this as fix is merged #576
