### ISSUE TITLE
add a github action/workflow to periodically sync docker images we use

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#585]
**Is your feature request related to a problem? Please describe.**

`golang` is an image we use for our ci/cd and to release images, and often there are bugfixes. It is there imperative that we keep docker://golang:xyz in sync with ghcr.io/project-zot/golang:xyz

**Describe the solution you'd like**

Pls. take a look at:
https://github.com/pulumi/pulumi-docker-containers/issues/64

**Comment by peusebiu** [comment]
I tried coming up with a regex matching all golang versions bigger than 1.18 (1.18.1, 1.18.2, 1.20 etc) but didn't make it.
With such regex we could use skopeo sync to periodically sync them.

I also made a manual workflow to sync any image:tag (as input) but figured out that we will have problems with permissions, not all users will have the permission to push to ghcr.io so it beats the purpose.

In the link you posted they are also doing it manually with version as input.
