### ISSUE TITLE
add `regclient` to ecosystem tools github action

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#586]
**Is your feature request related to a problem? Please describe.**

We currently verify against skopeo and oras. We should also do `regclient`.

**Describe the solution you'd like**

https://github.com/regclient/regclient

**Comment by bogdanbiv** [comment]
makefile test regclient exists, install if missing

add to Zot blackbox push-pull tests
- regclient pull OCI image (if there is an image already in Zot)
- regclient push new OCI image

**Comment by rchincha** [comment]
> makefile test regclient exists, install if missing
> 
> add to Zot blackbox push-pull tests (test/blackbox/pushpull.bats)
> 
>     * regclient pull OCI image (if there is an image already in Zot)
> 
>     * regclient push new OCI image

We can add the install step in the github workflow instead of in the Makefile, fwiw

**Comment by andaaron** [comment]
Done in #668
