### ISSUE TITLE
ui: add a freeform "search" api (with boltdb support)

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#591]
**Is your feature request related to a problem? Please describe.**

Currently, we have graphQL APIs for very specific use cases. 
We need a "freeform" search API which does the following:
given a string, return a top-K list of descriptors and types (repo, image, layer-hash) containing that string.

**Describe the solution you'd like**

Create a new API that behaves like above.

**Comment by rchincha** [comment]
Given a substring (not regex), return a list of results.

Dynamic search:
* Given a substring, return a list of top-K results of each type (repo, image:tag, layer hash)

Paginated search:
* Given a substring, return a list of results (repo, image:tag, layer hash) with paginated search (/query?offset=15&limit=15)

**Comment by andaaron** [comment]
I propose we have a single API, and the results would be ordered by relevance.
For the dynamic search, we would only show the 1st page, which would contains the most relevant K results.
Laurentiu has a ideas on the criteria according to which the search results would be more relevant than others.

**Comment by andaaron** [comment]
Let's keep track of this for the DB related work for servicing graphql requests.
The GQL side changes were already merged.

**Comment by andaaron** [comment]
In review https://github.com/project-zot/zot/pull/979/commits
