### ISSUE TITLE
ui: add a new API to store and retrieve user-specific metadata such as favorites

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#592]
**Is your feature request related to a problem? Please describe.**

zot UI intends to store and retrieve user-specific metadata such as favorites, stars, etc for repos and images.

**Describe the solution you'd like**

Design and implement an API. This can be under UI extension in the config.

**Comment by rchincha** [comment]
landing page

    For favorites, call the new /username/favorites api
    For recently updated packages, call the updated /imageListWithLatestTag api, and identify recently updated packages with new flag isRecentlyUpdated

explore page
Add these properties in existing ImageListWithLatestTag

    isRecentlyUpdated
    isSigned
    downloads
    Rating (rank)
    Stars (count)

Add these properties in existing expanded repo info api ExpandedRepoInfo
At manifest level:

    lastUpdated

At layer level:

    OS/Arch

For Dependencies

    New API to get list of dependencies for all versions

For Dependants

    New API to get list of dependants for all versions

**Comment by andaaron** [comment]
TODO: write a document to design "State management in zot"

**Comment by andaaron** [comment]
In testing: https://github.com/project-zot/zot/pull/968/commits/0470527795de7a97c7fe765492af62a28cdbdc48
