### ISSUE TITLE
Create a repo for zot on artifacthub.io for publishing helm charts

### ISSUE THREAD

**Issue by Andreea-Lupu** [project-zot/zot#604]
We need to create an account and a repo (or maybe an organization  and add a repository to it) on artifacthub.io in order to publish in an automated way our helm chart for zot.

The value for the Url field should be: http://zotregistry.io/helm-charts/

![image](https://user-images.githubusercontent.com/58118008/177811372-02fd53ba-bed2-4cd2-8bd3-db1121c1e9da.png)

https://artifacthub.io/
https://artifacthub.io/docs/topics/repositories/

**Comment by andaaron** [comment]
This was done.
