### ISSUE TITLE
Add graphql playground to zot

### ISSUE THREAD

**Issue by bogdanbiv** [project-zot/zot#606]
**Is your feature request related to a problem? Please describe.**
Nice to have: documenting APIs in an user interactive way (like Swagger/OpenAPI UIs)

**Describe the solution you'd like**
Graphql playground allows self documenting APIs. Possible implementation (candidates): https://github.com/graphql-go/playground

**Describe alternatives you've considered**
 * Postman
 * cURL
 * graphqlbin https://www.graphqlbin.com/v2/6RQ6TM

**Additional context**
<img width="674" alt="GraphQL API Playground for SWAPI - The Star Wars API Database Hub" src="https://user-images.githubusercontent.com/104334/177834345-a8c1b531-7246-42c4-aca5-21b1a482dac9.png">

Demo workhorse 
 + https://swapi-graphql.netlify.app/.netlify/functions/index, 
 + https://swapi-graphql.netlify.app

**Comment by andaaron** [comment]
Also interesting to look at: https://github.com/graphql/graphiql
