### ISSUE TITLE
crane cp fails

### ISSUE THREAD

**Issue by tamalsaha** [project-zot/zot#622]
**Describe the bug**
I tried to upload using [crane](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md) and it failed.

```
bin/zot-darwin-arm64 serve examples/config-minimal.json

{"level":"info","module":"http","clientIP":"127.0.0.1:54199","method":"HEAD","path":"/v2/busybox/blobs/sha256:62aedd01bd8520c43d06b09f7a0f67ba9720bdc04631a8242c65ea995f3ecac8","statusCode":200,"latency":"498.167µs","bodySize":0,"headers":{"User-Agent":["crane/0.10.0 go-containerregistry/(devel)"]},"goroutine":82,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2022-07-13T10:57:01.683065-07:00","message":"HTTP API"}
{"level":"info","module":"http","clientIP":"127.0.0.1:54199","method":"PUT","path":"/v2/busybox/manifests/sha256:dcdf379c574e1773d703f0c0d56d67594e7a91d6b84d11ff46799f60fb081c52","statusCode":415,"latency":"6.292µs","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Content-Length":["527"],"Content-Type":["application/vnd.docker.distribution.manifest.v2+json"],"User-Agent":["crane/0.10.0 go-containerregistry/(devel)"]},"goroutine":82,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2022-07-13T10:57:01.683779-07:00","message":"HTTP API"}
```

```
> crane cp busybox localhost:8080/busybox:latest

2022/07/13 10:57:00 Copying from busybox to localhost:8080/busybox:latest
2022/07/13 10:57:01 existing blob: sha256:19d511225f94f9b5cbf3836eb02b5273c01b95da50735742560e3e45b8c8bfcc
2022/07/13 10:57:01 existing blob: sha256:62aedd01bd8520c43d06b09f7a0f67ba9720bdc04631a8242c65ea995f3ecac8
Error: failed to copy index: PUT http://localhost:8080/v2/busybox/manifests/sha256:dcdf379c574e1773d703f0c0d56d67594e7a91d6b84d11ff46799f60fb081c52: unexpected status code 415 Unsupported Media Type
```

**To Reproduce**
1. Configuration
2. Client tool used
3. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rchincha** [comment]
@tamalsaha Thanks for filing the issue.

`zot` is a OCI dist-spec-only registry which means clients need to be conformant as well. That said, investigating this.

Meanwhile, would it be possible for you to consider `skopeo` instead?
https://github.com/project-zot/zot#skopeo

**Comment by tamalsaha** [comment]
Thanks for the quick response. I just tried skopeo but I am getting http/https error. I am running zot binary locally. I am not sure how to tell skopeo to not use https.

```
> ./bin/zot-darwin-arm64 serve examples/config-minimal.json
{"level":"info","params":{"distSpecVersion":"1.0.1-dev","GoVersion":"go1.18.4","Commit":"v1.4.2-rc2-8-g8da34d5","BinaryType":"-sync-search-scrub-metrics-ui_base","AccessControl":null,"Storage":{"Dedupe":true,"GC":true,"Commit":false,"GCDelay":3600000000000,"GCInterval":0,"RootDirectory":"/tmp/zot","StorageDriver":null,"SubPaths":null},"HTTP":{"Address":"127.0.0.1","Port":"8080","AllowOrigin":"","TLS":null,"Auth":{"FailDelay":0,"HTPasswd":{"Path":""},"LDAP":null,"Bearer":null},"RawAccessControl":null,"Realm":"","AllowReadAccess":false,"ReadOnly":false,"Ratelimit":null},"Log":{"Level":"debug","Output":"","Audit":""},"Extensions":null},"goroutine":1,"caller":"zotregistry.io/zot/pkg/api/controller.go:107","time":"2022-07-13T11:13:44.818818-07:00","message":"configuration settings"}
{"level":"info","cpus":8,"max. open files":65535,"goroutine":1,"caller":"zotregistry.io/zot/pkg/api/controller.go:102","time":"2022-07-13T11:13:44.818856-07:00","message":"runtime params"}
```

```
> skopeo copy --format=oci docker://busybox docker://localhost:8080/busybox --multi-arch=all
Getting image list signatures
Copying 10 of 10 images in list
Copying image sha256:dcdf379c574e1773d703f0c0d56d67594e7a91d6b84d11ff46799f60fb081c52 (1/10)
Getting image source signatures
FATA[0001] trying to reuse blob sha256:19d511225f94f9b5cbf3836eb02b5273c01b95da50735742560e3e45b8c8bfcc at destination: pinging container registry localhost:8080: Get "https://localhost:8080/v2/": http: server gave HTTP response to HTTPS client
```

**Comment by rchincha** [comment]
Since you haven't setup TLS certs yet, also use `--dest-tls-verify=false` like so:

`skopeo copy --format=oci --dest-tls-verify=false docker://busybox docker://localhost:8080/busybox --multi-arch=all`

**Comment by tamalsaha** [comment]
Thanks. The tls issue solved. But I see a new error.

```
> skopeo copy --format=oci --dest-tls-verify=false docker://busybox docker://localhost:8080/busybox --multi-arch=all
Getting image list signatures
Copying 10 of 10 images in list
Copying image sha256:dcdf379c574e1773d703f0c0d56d67594e7a91d6b84d11ff46799f60fb081c52 (1/10)
Getting image source signatures
Copying blob 19d511225f94 skipped: already exists
Copying config 5adc2f9fad done
Writing manifest to image destination
Storing signatures
Copying image sha256:897ee244eb86a38fa6f7d21e6a9e22aae41f105c574fc47b2c77cff8be98e29d (2/10)
Getting image source signatures
Copying blob 94b622d2880b done
Copying config 3cb910bc00 done
Writing manifest to image destination
Storing signatures
Copying image sha256:da1b5115bf7e41d123977962115034c67d019ef63fc0c3b9ddfdea3b6f9f9992 (3/10)
Getting image source signatures
Copying blob 7bc0df393b28 done
Copying config 54929f90e2 done
Writing manifest to image destination
Storing signatures
Copying image sha256:c940f8509c36033b11bd7468bf9d9cb60b51f4be13033cfe70e86581944d66cc (4/10)
Getting image source signatures
Copying blob 7ceae7886eaf done
Copying config 6bfc8b040c done
Writing manifest to image destination
Storing signatures
Copying image sha256:2c5e2045f35086c019e80c86880fd5b7c7a619878b59e3b7592711e1781df51a (5/10)
Getting image source signatures
Copying blob 87379020f3b6 done
Copying config 4463ac2fb2 done
Writing manifest to image destination
Storing signatures
Copying image sha256:0dc78806f5885db569f7389b0e0df2e190346b0df59937268c5862d5bfc5f933 (6/10)
Getting image source signatures
Copying blob 122c52305f25 done
Copying config cd1da0766e done
Writing manifest to image destination
Storing signatures
Copying image sha256:d339093e7bda33949fb5f3ddb6eeb6b51b8b0950183a132831c74cba05f0a1ea (7/10)
Getting image source signatures
Copying blob ff2d9c2b154f done
Copying config 353683d1a1 done
Writing manifest to image destination
Storing signatures
Copying image sha256:0d4b25aec0a40382a3eaea29e3af360f2c5908c91b3b12ded5492fdc5e74050c (8/10)
Getting image source signatures
Copying blob cd719190bb51 done
Copying config 39fcd2b22a done
Writing manifest to image destination
Storing signatures
Copying image sha256:3cb3c11a9bac8d6ca264766461deae86cdd58c174ecb26cdf2222e8e489c4132 (9/10)
Getting image source signatures
Copying blob 46b5947a368c done
Copying config 1b73bdb9af done
Writing manifest to image destination
Storing signatures
Copying image sha256:ac0e2006c03b435ee605c4bf84464d9fb665353643fa6295962bd69c23ced5dc (10/10)
Getting image source signatures
Copying blob 55b62457923c done
Copying config 8ae09c4662 done
Writing manifest to image destination
Storing signatures
Writing manifest list to image destination
FATA[0019] Uploading manifest list failed, attempted the following formats: application/vnd.oci.image.index.v1+json(uploading manifest latest to localhost:8080/busybox: StatusCode: 415, )
```

```
{"level":"info","module":"http","clientIP":"127.0.0.1:54865","method":"PUT","path":"/v2/busybox/manifests/latest","statusCode":415,"latency":"3.5µs","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Connection":["close"],"Content-Length":["2166"],"Content-Type":["application/vnd.oci.image.index.v1+json"],"Docker-Distribution-Api-Version":["registry/2.0"],"User-Agent":["skopeo/1.8.0"]},"goroutine":233,"caller":"zotregistry.io/zot/pkg/api/session.go:132","time":"2022-07-13T11:39:05.238791-07:00","message":"HTTP API"}
```

**Comment by rchincha** [comment]
Can you try dropping the `--multi-arch=all` argument?

**Comment by rchincha** [comment]
Just FYI, another client which we know is fully OCI compliant is [`regclient`](https://github.com/regclient/regclient).

**Comment by rchincha** [comment]
> Can you try dropping the `--multi-arch=all` argument?

Another issue is you have specified any image tag on the destination side, which is not OCI compliant.
`docker://localhost:8080/busybox:latest` instead?
 Would try this first.

**Comment by shimish2** [comment]
Hi @tamalsaha,

It is failing since --multi-arch is sending an image index to an URI endpoint which expects a image manifest.

However, you can override os and arch in `skopeo` as follows: 

``` 
skopeo --override-arch=amd64 --override-os=linux copy --format=oci --dest-tls-verify=false docker://busybox:latest docker://localhost:8080/busybox:latest
```

**Comment by shimish2** [comment]
busybox on dockerhub only has limited arch/os combinations available. Following is a trace on a Mac running zot.

```
skopeo --override-arch=amd64 --override-os=darwin copy --format=oci --dest-tls-verify=false docker://busybox:latest docker://localhost:8080/busybox:latest
FATA[0001] choosing an image from manifest list docker://busybox:latest: no image found in manifest list for architecture amd64, variant "", OS darwin 
```

```
skopeo --override-arch=arm64 --override-os=linux copy --format=oci --dest-tls-verify=false docker://busybox:latest docker://localhost:8080/busybox:latest
Getting image source signatures
Copying blob 87379020f3b6 skipped: already exists
Copying config 4463ac2fb2 done
Writing manifest to image destination
Storing signatures
```

**Comment by sudo-bmitch** [comment]
From my testing, it doesn't look like Zot supports the Docker media types, or the OCI Index media type, only the OCI Image. That means multi-platform manifests can't be copied, but I can copy single platform images, by name or digest, as long as the media type is `application/vnd.oci.image.manifest.v1+json`.

**Comment by sudo-bmitch** [comment]
That limitation on media types is confirmed here:
https://github.com/project-zot/zot/blob/ada21ed84237e858892d436c677bddeddd189342/pkg/storage/local.go#L1556-L1559

**Comment by rchincha** [comment]
@sudo-bmitch,

As per the spec,
https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pushing-manifests

**Comment by sudo-bmitch** [comment]
The index manifest is frequently used (along with the docker media types), so I'm a bit surprised to see they aren't supported:
https://github.com/opencontainers/image-spec/blob/main/image-index.md

**Comment by rchincha** [comment]
Adding @jdolitsky to the discussion here.

Multi-arch image push as done by `skopeo` pushes as oci image index to the manifests endpoint, while `zot` expects an oci image manifest. Not clear if `zot` is non-compliant, but if so, we would like to fix it.

**Comment by jdolitsky** [comment]
It may have to do with the busybox image being of Docker type vs OCI:
```
$ crane manifest busybox  | jq -r .mediaType
application/vnd.docker.distribution.manifest.list.v2+json
```

You would want to use something to convert it instead of direct `crane cp`

**Comment by tamalsaha** [comment]
@rchincha , do you see Zot supporting common Docker images like busybox as-is or require some kind of conversion to be uploaded to a Zot registry? I understand that this might require supporting more than just the OCI spec.

**Comment by rchincha** [comment]
`zot` aims to be **vendor-neutral** which means staying close to OCI standards. So, short answer is NO.
But for all practical purposes, this is seldom a serious limitation (also from our experience) since there are plenty of tools that do the conversion (`skopeo` does too)

**Comment by tamalsaha** [comment]
I have never used `skopeo` before yesterday. How will oen copy this busybox image into zot registry? How do I convert the manifest?

**Comment by rchincha** [comment]
`skopeo --override-arch=arm64 --override-os=linux copy --format=oci --dest-tls-verify=false docker://busybox:latest docker://localhost:8080/busybox:latest`

^ is your ask different from this?

**Comment by tamalsaha** [comment]
Yes, because this command will only upload the linux/arm64 image. I want to upload images for all the architectures that busybox has on Docker hub . Then also upload the manifest that points to those uploaded architecture specific images.

**Comment by sudo-bmitch** [comment]
The downside of converting manifests to the OCI media types is the digest is modified in the process. That means you can no longer include image signing metadata on the image, and users cannot pin to a digest from a trusted external source. Tools that do the conversion aren't that widespread, and tools to build container images still strongly favor the Docker media types.

**Comment by rchincha** [comment]
True. @tamalsaha pls evaluate if this is a serious limitation for you - basically, cross-repo copying and cross-repo references.

That said, if you want to control your entire pipeline ...

https://github.com/project-stacker/stacker
https://github.com/chainguard-dev/apko
https://github.com/sigstore/cosign

PS: we are rolling out a -rc release to address the multi-arch requirement.

**Comment by rchincha** [comment]
> True. @tamalsaha pls evaluate if this is a serious limitation for you - basically, cross-repo copying and cross-repo references.
> 
> That said, if you want to control your entire pipeline ...
> 
> https://github.com/project-stacker/stacker https://github.com/chainguard-dev/apko https://github.com/sigstore/cosign
> 
> PS: we are rolling out a -rc release to address the multi-arch requirement.

@tamalsaha https://github.com/project-zot/zot/releases/tag/v1.4.2-rc5 is now available which should address the multi-arch requirement.

**Comment by rchincha** [comment]
@tamalsaha FYI, https://github.com/project-zot/zot/releases/tag/v1.4.2 is now officially released which includes the multi-arch support.

**Comment by itaysk** [comment]
I get the impression this issue is resolved, but I'm still getting this with latest zot

```
❯ regctl image copy nginx:1.22.1 localhost:5000/nginx:1.22.1
WARN[0004] Failed to push manifest                       err="failed to put manifest localhost:5000/nginx@sha256:5bbe9f58a36db5fd0b65a59134c0342b9fc111ef2ade5887ae923ac4d3bafe23: request failed: unexpected http status code: Unsupported Media Type [http 415]: {\"errors\":[{\"code\":\"MANIFEST_INVALID\",\"message\":\"manifest invalid\",\"description\":\"During upload, manifests undergo several checks ensuring\\n\\t\\t\\tvalidity. If those checks fail, this error MAY be returned, unless a more\\n\\t\\t\\tspecific error is included. The detail will contain information the failed\\n\\t\\t\\tvalidation.\",\"detail\":[{\"mediaType\":\"application/vnd.docker.distribution.manifest.v2+json\"}]}]}" target="localhost:5000/nginx:1.22.1"
failed to put manifest localhost:5000/nginx@sha256:5bbe9f58a36db5fd0b65a59134c0342b9fc111ef2ade5887ae923ac4d3bafe23: request failed: unexpected http status code: Unsupported Media Type [http 415]: {"errors":[{"code":"MANIFEST_INVALID","message":"manifest invalid","description":"During upload, manifests undergo several checks ensuring\n\t\t\tvalidity. If those checks fail, this error MAY be returned, unless a more\n\t\t\tspecific error is included. The detail will contain information the failed\n\t\t\tvalidation.","detail":[{"mediaType":"application/vnd.docker.distribution.manifest.v2+json"}]}]}
```

am I doing something wrong?

**Comment by sudo-bmitch** [comment]
@itaysk, see @rchincha's comment above, only the OCI media types are supported, not the docker ones: https://github.com/project-zot/zot/issues/622#issuecomment-1184655793

**Comment by ktarplee** [comment]
This is a major limitation of Zot in any real environment and should be documented clearly as an intentional limitation in the readme.

**Comment by saggiyogesh** [comment]
**Update:**
`skopeo copy docker://nginx docker://custom-zot-reg.com/nginx`

This works well as expected although there's no need to add the flag `--format=oci` in the copy command.
