### ISSUE TITLE
support OCI image index media-type on manifests endpoint

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#640]
**Is your feature request related to a problem? Please describe.**

Currently, `zot` only allows uploading individual images. It is also possible to upload multiple images in the form of a OCI image index, for example, in multi-arch image upload.

- [ ] add push/pull support
- [ ] add unit tests
- [ ] resolve delete support
- [ ] resolve tags listing, catalog
- [ ] add ecosystem tool verification

**Comment by thesayyn** [comment]
@rchincha I'd be happy to help with this if you need any.

**Comment by rchincha** [comment]
@thesayyn, appreciate the offer to help. We already have a PR which should be merged soon.
Do you want to look over https://github.com/project-zot/zot/labels/good%20first%20issue for any unassigned issues that might interest you?
