### ISSUE TITLE
GraphQL API: ImageSummary and RepoSummary to include download counters

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#658]
**Is your feature request related to a problem? Please describe.**
A freeform search API was introduced in https://github.com/project-zot/zot/issues/591 / https://github.com/project-zot/zot/pull/618
This API should support also return counters for images/repos:
- DownloadCount for images
- DownloadCount for repos

Note currently we do not store this data, we need an enhancement as part of https://github.com/project-zot/zot/issues/538

**Describe the solution you'd like**
The graphql API results should also return DownloadCount as part of the results for images and repos.

**Additional context**
This is needed for the `zui` functionality - in both the general search view with results as cards.

**Comment by raulkele** [comment]
For the current zui design, DownloadCount is only needed for repos but the repo DownloadCount will most likely be the sum of all the downloads of images in the repo, returning download counter for images might be useful in the future.

**Comment by andaaron** [comment]
In review
