### ISSUE TITLE
Freeform search API: include user specific metadata

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#659]
**Is your feature request related to a problem? Please describe.**
A freeform search API was introduced in https://github.com/project-zot/zot/issues/591 / https://github.com/project-zot/zot/pull/618
This API should include user specific information as part of search results.

Note currently we do not store this data, we need an enhancement as part of https://github.com/project-zot/zot/issues/592

**Describe the solution you'd like**
This API should include user specific information as part of search results:
- StarCount for images - number of users which have starred the image
- StarCount for repos - number of users which have starred the repo
- IsBookmarked for image - true if current user has bookmarked his image
- IsBookmarked for repo -  true if current user has bookmarked his repo
- The image/repo "relevance"/"score" should take into account if the user has starred/bookmarked the specific image/repo. Bookmarks having the highest score, if they martially match the search string, followed by starred repos if they partially matched the search string.

**Additional context**
This is needed for the `zui` functionality - in both the general search view with results as cards.

**Comment by andaaron** [comment]
We could split this issue if it is too large for a single PR.

**Comment by raulkele** [comment]
For the current design goal of zui, starring/bookmarking individual images is not something we want to support, only starring/bookmarking a repo. This might change in future iterations of the zui design.
