### ISSUE TITLE
Investigate using Auth0's JWT library

### ISSUE THREAD

**Issue by bogdanbiv** [project-zot/zot#699]
**Is your feature request related to a problem? Please describe.**
Auth0 provides a nice framework that supports LDAP and many other auth backends

**Describe the solution you'd like**
a nice and simple way to obtain a secure JWT
a simple way to pass JWT in HTTP headers for authenticated HTTP calls

**Describe alternatives you've considered**
we should not implement authentication strategies ourselves;
maybe there are alternatives to Auth0, I have not considered them yet

**Additional context**
 * Step 1 Add auth0 support
 * Step 2 ...
 * Step 3 Profit!

Examples:
https://github.com/auth0-samples/auth0-golang-api-samples/tree/master/01-Authorization-RS256

**Comment by andaaron** [comment]
We don't need this anymore, given current OIDC implementation.
