### ISSUE TITLE
GraphQL: API to retrieve the list of repos/tags a layer is part of

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#703]
ImageListForLayerDigest(digest: String!): [ImageSummary!]

**Comment by peusebiu** [comment]
We already have this one which covers the requirement of this task. The single drawback is that is not specific for layers, it will search layers digest + config blob digest + manifest digest

ImageListForDigest(digest: String!); [ImageSummary!]

Why do we need it a similar one?

**Comment by andaaron** [comment]
We don't need this anymore.
