### ISSUE TITLE
Modify swagger target to verify swagger docs are up to date

### ISSUE THREAD

**Issue by bogdanbiv** [project-zot/zot#708]
**Describe the bug**
Modify swagger target to verify swagger docs are up to date

**To Reproduce**
 * unify swagger version across zot (v1.3.0, 1.6.3, v1.6.3, latest, no tagged version)
 * move commited OpenAPI docs
 * regenerate OpenAPI docs
 * compare regenerated OpenAPI docs with commit (TBD: warn / error?)

what's the difference between `swagger.json` and `swagger.yaml`?
**Expected behavior**

**Screenshots**

**Additional context**

**Comment by andaaron** [comment]
Partially fixed in https://github.com/project-zot/zot/pull/1701
What is missing the CI/CD verification step for uncommitted files.

**Comment by andaaron** [comment]
Fixed in #1724
