### ISSUE TITLE
authN: support GitHub authentication

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#709]
**Is your feature request related to a problem? Please describe.**

GitHub can be used as an authenticator. It is useful when developers are on GitHub and is desirable to avoid separately managing authentication for zot.

**Describe the solution you'd like**

https://github.com/google/go-github
https://github.com/google/go-github/blob/master/example/basicauth/main.go

**Comment by andaaron** [comment]
This library can also be used with OAuth2 (golang.org/x/oauth2).

See an example at:
https://blog.kowalczyk.info/article/f/accessing-github-api-from-go.html

**Comment by andaaron** [comment]
Fixed in #1381
