### ISSUE TITLE
authN: support GitLab authentication

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#710]
**Is your feature request related to a problem? Please describe.**

GitLab can be used as an authenticator. It is useful when developers are on GitLab and is desirable to avoid separately managing authentication for zot.

**Describe the solution you'd like**

https://github.com/xanzy/go-gitlab
https://github.com/xanzy/go-gitlab/blob/master/gitlab.go

**Comment by rchincha** [comment]
This is related to issue #709

**Comment by andaaron** [comment]
Fixed in #1381
