### ISSUE TITLE
release checksums.txt along with every release.

### ISSUE THREAD

**Issue by thesayyn** [project-zot/zot#715]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to check the integrity of prebuilt binaries as there is no checksum published alongside prebuilt binaries. 

**Describe the solution you'd like**
Release of `checksum.txt` or `<binary_name>.sig` file containing the checksum with each release.

**Describe alternatives you've considered**
Downloading each binary and taking checksum of each file

**Additional context**
A few examples of this 
https://github.com/sigstore/cosign/releases
https://github.com/google/go-containerregistry/releases

**Comment by vrajashkr** [comment]
Thinking out loud, a potential approach might be along the lines of having a dedicated checksum file for each hash algorithm for each build artifact.

For example, for the artifact named `zot-linux-amd64-minimal`, there would be a file named `zot-linux-amd64-minimal.sha256sum` that contains the SHA256 hash for this artifact.

**Comment by rchincha** [comment]
https://github.com/marketplace/actions/generate-release-hashes
https://github.com/marketplace/actions/generate-checksum
