### ISSUE TITLE
FR: print which port the registry listening on

### ISSUE THREAD

**Issue by thesayyn** [project-zot/zot#717]
**Is your feature request related to a problem? Please describe.**
When port `zero (0)` is used in the HTTP configuration, there is no way to determine which port registry is listening on.

**Describe the solution you'd like**
`zot serve` tells us which port it is listening on

**Describe alternatives you've considered**
using os utilities like netstat / lsof to find out the port by using the PID.

**Additional context**

**Comment by rchincha** [comment]
Best to make it explicit in the configuration and enforce that port is never zero.

**Comment by thesayyn** [comment]
> Best to make it explicit in the configuration and enforce that port is never zero.

That would be the best for common use cases but when it comes to spawning multiple isolated registries this becomes annoying. Imagine spawning hundreds of these registries. 

Using port zero is the only way to ensure that you'll always get a free port until you ran out of them which is unlikely. Other approaches I have considered so far have no way of ensuring that you won't get an error.

This is part of Unix and zot & golang seem to support it already. The only missing piece is the information about which port is bound. Would you accept if this was debug information rather than regular info polluting the console?

Also, is there a reason why you are against it?

**Comment by rchincha** [comment]
> That would be the best for common use cases but when it comes to spawning multiple isolated registries this becomes annoying. Imagine spawning hundreds of these registries.

The only "common" use case would be perhaps for IoT deployments. Is this what you had in mind?
So the issue then becomes - "don't want to configure each individual instance, but would like to know what port got picked"
In agreement so far?

**Comment by thesayyn** [comment]
> The only "common" use case would be perhaps for IoT deployments. Is this what you had in mind?
> So the issue then becomes - "don't want to configure each individual instance, but would like to know what port got picked"

My use case is different but suffers from the same problem you just described. And yes that'd be enough if each individual registry printed what port "os assigned to them"

**Comment by thesayyn** [comment]
@rchincha I could take this if this sounds reasonable.

**Comment by rchincha** [comment]
> @rchincha I could take this if this sounds reasonable.

Sure.

"When port is missing or specified as zero, print an additional (we already print entire config we read as-is) INFO msg to report what port got picked."

**Comment by mwopfner** [comment]
Would it also be possible to add a method to the `Controller` over which the actual assigned address (`GetAddr()`) can be read.
I'm using zot as a library in my on app and want to start a zot server on some random available port. Then I communicate with an other device and tell it where to pull my images from, which is the server I have started. 
I have everything working with a fixed port, but to be more robust and not relay on any port that must always be free I would prefer a randomly assigned port.

**Comment by rchincha** [comment]
@mwopfner can you pls review https://github.com/project-zot/zot/pull/770 and see if this would work for you?

**Comment by mwopfner** [comment]
@rchincha Yes, that is exactly what I have needed.
