### ISSUE TITLE
FR: `loose` mode allowing Docker mediaTypes 

### ISSUE THREAD

**Issue by thesayyn** [project-zot/zot#724]
**Is your feature request related to a problem? Please describe.**
Right now only OCI standard mediaTypes are allowed and anything else gets rejected such as Docker V2 Manifest and ManifestList

**Describe the solution you'd like**
It would help a lot to have a loose mode where Docker V2 images are allowed to be stored inside the registry.

**Describe alternatives you've considered**
Converting docker v2 images to be have OCI mediaTypes and Config but that breaks provenance as signatures change due to mediaTypes and Config changes during conversion.

**Additional context**
I know the whole point of zot is to be vendor-neutral but I believe it would help a lot of people if we allowed this. Also, docker v2 images are mostly used image format in the wild.

PS: I noticed that zot does not enforce what mediaType `config/blobs` has as long as their descriptors use OCI standard mediaTypes.

Likely to prevent issues such as #622

**Comment by rchincha** [comment]
> Describe the solution you'd like
It would help a lot to have a loose mode where Docker V2 images are allowed to be stored inside the registry.

Describe alternatives you've considered
Converting docker v2 images to be have OCI mediaTypes and Config but that breaks provenance as signatures change due to mediaTypes and Config changes during conversion.

@thesayyn thanks for taking a deep dive into zot.

This particular topic has been debated internally and our current position is that if you want to be in docker ecosystem, the best docker registry is really the "docker distribution" itself.

`zot` is positioned to be a good fit in the OCI ecosystem, which means one builds OCI natively [1], signs OCI [2][3], and pushes/pulls OCI to/from zot.

References:
[1] https://github.com/project-stacker/stacker
[2] https://github.com/sigstore/cosign
[3] https://github.com/notaryproject/notation

**Comment by thesayyn** [comment]
> `zot` is positioned to be a good fit in the OCI ecosystem, which means one builds OCI natively [1], signs OCI [2][3], and pushes/pulls OCI to/from zot.

I get that but I don't see how allowing `docker v2` images would break this given they are backward compatible with each other just lacking a bit of information between the two formats. Perhaps I am missing something here?

> This particular topic has been debated internally and our current position is that if you want to be in the docker ecosystem, the best docker registry is really the "docker distribution" itself.

Using distribution is one option, but that wouldn't work for the use case I have in mind as it is supposed to be used with a container runtime using the official images.   Also, provides only Linux binaries which I don't think going to change anytime soon. 

As far as I can tell zot already supports `Docker v2` if relevant lines are made conditional.

https://github.com/project-zot/zot/blob/a702a2377e4baf8009c3a81070c0ed2e8f41c936/pkg/storage/local.go#L552
https://github.com/project-zot/zot/blob/a702a2377e4baf8009c3a81070c0ed2e8f41c936/pkg/api/routes.go#L438

**Comment by rchincha** [comment]
> Using distribution is one option, but that wouldn't work for the use case I have in mind as it is supposed to be used with a container runtime using the official images. 

@thesayyn Could you elaborate on this some more?

**Comment by thesayyn** [comment]
> > Using distribution is one option, but that wouldn't work for the use case I have in mind as it is supposed to be used with a container runtime using the official images.
> 
> @thesayyn Could you elaborate on this some more?

Using the distribution requires you to be on Linux as they only publish Linux images and binaries which is not feasible for my use case. I need to run a registry that is platform agnostic and can run on Linux and Darwin and optionally on windows.

**Comment by rchincha** [comment]
@thesayyn maybe fairly simple to just build docker distribution/registry binaries from source for your arch/os. Did you consider that?

**Comment by thesayyn** [comment]
Yes. This is not preferable as there is no guarantee that it wouldn’t break with a random commit given the lack of testing for the platforms that I am building.  Also, requires me to publish prebuilt binaries with each version.

**Comment by thesayyn** [comment]
@rchincha Any thoughts? We'd really benefit from this as a backward compatibility feature in https://github.com/bazel-contrib/rules_oci. As far as you are concerned signing is completely unrelated to what media type is the image using. cosign does not care if you are using docker media types or oci media types

**Comment by rchincha** [comment]
@thesayyn Supporting docker format on-the-wire but converting to OCI layout is probably something we could consider. But this means signatures, etc become invalid. Would this be acceptable for your use case?

**Comment by thesayyn** [comment]
@rchincha We discussed this over at https://github.com/google/go-containerregistry/pull/1293. signatures and sboms become more important each day so this implicit conversion might not be a good idea.

**Comment by rchamarthy** [comment]
@thesayyn for cross-platform build you need the build system itself to run on another platform. Curious about what other platforms you need to be supported?

**Comment by thesayyn** [comment]
> @thesayyn for cross-platform build you need the build system itself to run on another platform. Curious about what other platforms you need to be supported?

darwin/linux/windows. optionally other platforms such as freebsd.

**Comment by dtzar** [comment]
Is there a way to make `docker build` ***** via `buildx` or any other means be able to push to zot? @rchincha 

I get this when trying to push a docker built image to the latest zot:

```shell
Removing intermediate container 3c7624421517
 ---> 25c5addfd02d
Warning:  One or more build-args [TEXT] were not consumed
Successfully built 25c5addfd02d
Successfully tagged localhost:5000/hello-azure-golang:9b57448bbfc9f22e3[67]
The push refers to repository [localhost:5000/hello-azure-golang]
5f58d1899b3a: Preparing
59ed5b393ba8: Preparing
9fce6bd02a21: Preparing
59ed5b393ba8: Pushed
9fce6bd02a21: Pushed
5f58d1899b3a: Pushed
manifest invalid: manifest invalid
Error: Process completed with exit code 1.
```

**Comment by rchincha** [comment]
Can `docker` cli push to OCI compliant registries by talking OCI dist-spec on the wire directly?

Can do it in two steps.
1. Use docker/buildx to output OCI layout tar and then untar
https://docs.docker.com/engine/reference/commandline/buildx_build/#output

2. Use skopeo to copy from copy this layout into zot
```
skopeo copy --format=oci --dest-tls-verify=false oci:<layout>:tag docker://localhost:5000
```
https://github.com/containers/skopeo

This is the reason we had to write `stacker` to be/do OCI-native.

**Comment by thesayyn** [comment]
bumping into this again. I'd like really like to see this supported here. a significant number of images out in the wild still use docker media types today (not v1 but v2) and this mode would allow those images to be stored inside zot.  converting them on pulling seems like an option but these days lots of images ship with cosign signatures that are attached to it them via digests. 
given that digests change during the conversion process, it's a bad decision from supply chain security standpoint. plus, it eliminates the chance of blobs being mounted across repositories. 

I still don't see a problem allowing images with docker media types to be stored in zot behind a flag that is turned off by default. 

@rchincha would you reconsider this?

**Comment by rchincha** [comment]
@thesayyn Pls. don't get us wrong, absolutely see why this would be needed.

This is likely going to a fully vertical integrated stack (HTTP APIs, layout, interaction with zot-specific extensions) etc - so basically a parallel implementation of "docker distribution"-lite.

That said, do you want to consider submitting a PR and let's see how it looks like.

**Comment by sudo-bmitch** [comment]
@rchincha 
> This is likely going to a fully vertical integrated stack (HTTP APIs, layout, interaction with zot-specific extensions) etc - so basically a parallel implementation of "docker distribution"-lite.

This confuses me. Tools working with the Docker media types are still pushing/pulling with the OCI distribution-spec. The only difference is the media type of the manifest, which has all the same fields as the OCI manifests (which is why conversion tools are easy to build). I haven't dug into the Zot internals in a while, but I don't believe the API would need to change for this.

**Comment by rbojan** [comment]
This is currently the most commented and 👍  open Issue in this repository. It would be really nice if you reconsider support for allowing Docker mediaTypes.

If not, it would be nice that it is documented somewhere that zot doesn't support pushing/storing Docker images. We spent some time automating the installation of zot only to find out that it doesn't support Docker.

**Comment by rchincha** [comment]
> This is currently the most commented and 👍 open Issue in this repository. It would be really nice if you reconsider support for allowing Docker mediaTypes.
> 
> If not, it would be nice that it is documented somewhere that zot doesn't support pushing/storing Docker images. We spent some time automating the installation of zot only to find out that it doesn't support Docker.

https://zotregistry.io/latest/user-guides/user-guide-datapath/?#common-tasks-using-skopeo-for-oci-images

**Comment by ChristianCiach** [comment]
> `zot` is positioned to be a good fit in the OCI ecosystem, which means one builds OCI natively [1], signs OCI [2][3], and pushes/pulls OCI to/from zot.

As it stands, Zot currently also cannot store in-toto attestations created by Cosign: https://github.com/sigstore/cosign/issues/1397#issuecomment-1741529253

It looks like Cosign tries to store the attestations using docker-specific media-types.

**Comment by ChristianCiach** [comment]
After reading this and related issues and PRs, I want to challenge the definition of what it even means to be "vendor neutral".

It seems to be the interpretation of Zot that "vendor neutral" means to only support a very specific set of media types. This is "fine" (even though I don't fully agree with this definition for pragmatic purposes discusses here and elsewhere), but I don't think this is the only possible interpretation.

I think Zot could also be "vendor neutral" by being "vendor agnostic", as in "Zot doesn't care for the media types of the stored artifacts, except for additional features provided for specific media types like signatures".

**Comment by rchincha** [comment]
@ChristianCiach curious why cosign attestations are broken. `zot` already supports `cosign` sign/verify workflows.

**Comment by ChristianCiach** [comment]
@rchincha That's because cosign only implements (guarded behind an experimental flag) OCI support for signatures and sboms, but not for attestations. See https://github.com/sigstore/cosign/issues/1397#issuecomment-1431067711

**Comment by willzhang** [comment]
same here with v1.4.3
```
root@ubuntu:~# docker push 192.168.72.16:5000/ubuntu:latest
The push refers to repository [192.168.72.16:5000/ubuntu]
256d88da4185: Layer already exists 
manifest invalid: manifest invalid
```

**Comment by jangrewe** [comment]
I just ran into this issue, and this is really disappointing. I initially synced from my (regular) Docker registry and all the images were there and could be pulled, but now i tried building and pushing an image with `docker` and couldn't figure out why i kept on getting `HTTP 415` errors (in the `info` log) and `manifest invalid: manifest invalid` errors when pushing said image.

Zot looked so promising, but this is a showstopper for us.

**Comment by rchincha** [comment]
If you want to stay in the `docker` ecosystem, then your best bet is stay with tooling in that ecosystem - too many touch points wrt building, storing, running images that could be disruptive in terms of business risk. Understood it has its own issues and not perfect, but at least they are known.

If you want to standardize on OCI tooling, then we can confidently recommend `zot` - we put a lot of effort in our CI that various ecosystem tooling is compatible. In the long-term, you should definitely evaluate moving there - OCI being open standards, vendor-neutral etc.

We are definitely not tone-deaf on this particular issue though.

The main goal of `zot` was and continues to be "vendor-neutral" and that is the future in our opinion, and that is where our limited resources will be focused on. The ask in this issue is to relax this a bit and be "vendor-agnostic" and include `docker`. We are still evaluating wrt the impact/effort on various features - sync, scrub, etc. Any new code/capability means we will need to support it forever and that is the cost.

Nitpicking, `docker push` is the real deal breaker, `docker pull/run` works fine.

**Comment by rchincha** [comment]
Closing this issue until we revisit.

**Comment by thesayyn** [comment]
I don't think closing this is a good idea, as people continue filing new issues and maintainers will have to explain everytime why not yet.

**Comment by thesayyn** [comment]
Plus people raised a lot of fair points in this issue...

**Comment by rchincha** [comment]
Tools that can build and publish to OCI registries:

https://github.com/bazel-contrib/rules_oci
https://github.com/chainguard-dev/apko
https://github.com/project-stacker/stacker

**Comment by ChristianCiach** [comment]
Carvel Imgpkg also doesn't work:

* https://github.com/carvel-dev/imgpkg/issues/621

This is another blocker for us. The other blocker being Cosign attestations.

**Comment by ktarplee** [comment]
@rchincha Mentioned this in the comment above
> That said, do you want to consider submitting a PR and let's see how it looks like.

Sounds like if we want Zot to support docker media types someone needs to open a PR.  Then the maintainers could see how bad or easy it is to support Zot.  Maybe it could be put behind a config option (as mentioned above, `strict: true`).  I don't think any one cares to support docker v1 images in Zot so all we are talking about is v2 images and the only real difference is the media types and a few missing fields.   But `strict: false` could even let the implementation ignore the subtle differences between the compatible media types.  Maybe there is some bigger change that would be necessary that I am missing.

**Comment by rchincha** [comment]
A minimum viable candidate would be to get `docker push` working against authentication-enabled `zot`.

**Comment by luisdavim** [comment]
Looking at this  https://github.com/project-zot/zot/pull/1385 I don't really understand the big deal around this issue, if that's all that it takes why not do it? Being vendor agnostic/independent doesn't mean blocking specific vendors.

**Comment by andaaron** [comment]
It's not just that. We would need to read the image mediatypes, and populate the data in our internal DB for features such as search and the CVE scanner to work.

Also it is not clear to me if the docker client respects the OCI distribution spec, If I remember correctly there were some issues when pushing blobs in multiple chunks.
We don't want to go down the rabbit hole of supporting clients which may not implement the OCI spec correctly.

**Comment by luisdavim** [comment]
I see, what about some conversion midleware or proxy even, if you want to keep it separate?

**Comment by aldinokemal** [comment]
> Is there a way to make `docker build` * via `buildx` or any other means be able to push to zot? @rchincha
> 
> I get this when trying to push a docker built image to the latest zot:
> 
> ```shell
> Removing intermediate container 3c7624421517
>  ---> 25c5addfd02d
> Warning:  One or more build-args [TEXT] were not consumed
> Successfully built 25c5addfd02d
> Successfully tagged localhost:5000/hello-azure-golang:9b57448bbfc9f22e3[67]
> The push refers to repository [localhost:5000/hello-azure-golang]
> 5f58d1899b3a: Preparing
> 59ed5b393ba8: Preparing
> 9fce6bd02a21: Preparing
> 59ed5b393ba8: Pushed
> 9fce6bd02a21: Pushed
> 5f58d1899b3a: Pushed
> manifest invalid: manifest invalid
> Error: Process completed with exit code 1.
> ```

For Everyone who want to push from local to zot you can convert it to `.tar` then copy to zot server using `skopeo`
I have created sample how to do this [https://github.com/aldinokemal/go-skopeo-zot-pusher](https://github.com/aldinokemal/go-skopeo-zot-pusher)

for Golang Developer you also able to direct install using 
- `go install github.com/aldinokemal/go-skopeo-zot-pusher@latest`
then
- `go-skopeo-zot-pusher push <image-name)`

**Comment by jangrewe** [comment]
This is getting ridiculous. I'm building an image with kaniko, which can produce OCI images, but as the base image (which i'm not going to rebuild) is not an OCI image, the output is a Docker image - which i then can't push.

Yes, you want to be OCI compliant. But The World™ isn't at that stage yet. You're shooting yourself in the foot, knee and balls by shutting out a large audience, which can't just switch 100% to OCI compliance... because that's not how it works.

This is really frustrating, and checking every couple of months to see if you guy showed any kind of understanding, but getting the same stubbornness, doesn't help with considering Zot as a viable container registry.

**Comment by rchincha** [comment]
@jangrewe does this workaround not work for you?

skopeo copy --format=oci <baseimage> into zot

Now, use _kaniko_ pointing to the <baseimage> in zot

**Comment by aldinokemal** [comment]
https://github.com/aldinokemal/go-oci

Hey, I just set up something super simple so you guys can run `push` and feel like you're using Docker!

for example
```
docker push localhost:5000/go-whatsapp-web-multidevice:linux-arm64 \
        --insecure=true
```

we can do

```
go-oci image:push localhost:5000/go-whatsapp-web-multidevice:linux-arm64 \
        --insecure=true
```

**Comment by rchincha** [comment]
IMHO, except for image signatures for originally docker images, there are two very viable workarounds:
1. setup zot as a sync/mirror pointing to upstream docker-only image registry
2. skopeo copy (or any other similar tool) into zot and then use

**Comment by jangrewe** [comment]
> very viable **workarounds**

... but still not solutions to be able use Zot as a **drop-in replacement** which doesn't require changing dozens of CI images to include either of those tools, and then thousands of CI pipelines to use those new images.

So: No, "workarounds" are not an option for us, which means Zot isn't an option.

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/pull/2714
^ no promises, but would encourage contributions/testing as we move this along

**Comment by rchincha** [comment]
> This is getting ridiculous. I'm building an image with kaniko, which can produce OCI images, but as the base image (which i'm not going to rebuild) is not an OCI image, so the output is a also Docker image - which i then can't push.

https://github.com/GoogleContainerTools/kaniko/issues/1836

A word of caution - it is not `zot`'s charter to solve all the client tooling issues ^

Can folks build a `zot` with this PR https://github.com/project-zot/zot/pull/2714 and test pls.
Some basic `docker push/pull` tests are working for us.

**Comment by andaaron** [comment]
Note, while #2714 was just merged to main, we still need to review the existing zot sync implementation. The code converting docker images from upstream to oci images locally was not touched in #2714

**Comment by rchincha** [comment]
v2.1.2-rc3 is now released which should include this PR.

**Comment by rchincha** [comment]
If installing from a container version, the "full"/default image version v2.1.2-rc3 should support docker out of the box.

**Comment by WhySoBad** [comment]
Hi,
I noticed the `rc3` as well as the newly released `rc4` still have an issue with the `application/vnd.docker.distribution.manifest.v2+json` media type.

As an example image one can use the `traefik/whoami` image. When trying to push the image I receive `manifest invalid: manifest invalid` and the following server log:
```
{"level":"info","module":"http","username":"admin","component":"session","clientIP":"xxx.xxx.xxx.xxx","method":"PUT","path":"/v2/whoami/manifests/latest","statusCode":415,"latency":"0s","bodySize":381,"headers":{"Accept-Encoding":["gzip"],"Authorization":["******"],"Content-Length":["948"],"Content-Type":["application/vnd.docker.distribution.manifest.v2+json"],"User-Agent":["docker/27.3.1 go/go1.23.1 git-commit/41ca978a0a kernel/6.12.6-arch1-1 os/linux arch/amd64 UpstreamClient(Docker-Client/27.3.1 \\(linux\\))"],"X-Forwarded-For":["xxx.xxx.xxx.xxx"],"X-Forwarded-Host":["my.registry.host"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Forwarded-Server":["asdfjkloe"],"X-Real-Ip":["xxx.xxx.xxx.xxx"]},"goroutine":43,"caller":"zotregistry.dev/zot/pkg/api/session.go:137","time":"2024-12-25T14:25:06.536985613Z","message":"HTTP API"}
```

**Comment by seniorquico** [comment]
> Hi, I noticed the `rc3` as well as the newly released `rc4` still have an issue with the `application/vnd.docker.distribution.manifest.v2+json` media type.
> 
> As an example image one can use the `traefik/whoami` image. When trying to push the image I receive `manifest invalid: manifest invalid` and the following server log:
> 
> ```
> {"level":"info","module":"http","username":"admin","component":"session","clientIP":"xxx.xxx.xxx.xxx","method":"PUT","path":"/v2/whoami/manifests/latest","statusCode":415,"latency":"0s","bodySize":381,"headers":{"Accept-Encoding":["gzip"],"Authorization":["******"],"Content-Length":["948"],"Content-Type":["application/vnd.docker.distribution.manifest.v2+json"],"User-Agent":["docker/27.3.1 go/go1.23.1 git-commit/41ca978a0a kernel/6.12.6-arch1-1 os/linux arch/amd64 UpstreamClient(Docker-Client/27.3.1 \\(linux\\))"],"X-Forwarded-For":["xxx.xxx.xxx.xxx"],"X-Forwarded-Host":["my.registry.host"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Forwarded-Server":["asdfjkloe"],"X-Real-Ip":["xxx.xxx.xxx.xxx"]},"goroutine":43,"caller":"zotregistry.dev/zot/pkg/api/session.go:137","time":"2024-12-25T14:25:06.536985613Z","message":"HTTP API"}
> ```

@WhySoBad Double check that you've enabled the API compatibility layer by merging the following into your zot config:

```json
{
  "http": {
    "compat": ["docker2s2"]
  }
}
```

Without this ^, I also get invalid manifest errors on the Docker media type. However, with this ^, I am able to push from my local Docker daemon:

![Image](https://github.com/user-attachments/assets/d933392d-759f-4857-8adb-510122cc1817)

**Comment by thesayyn** [comment]
@rchincha I am catching up again on this thread, sorry i didn't have time to implement this myself, and i also see lots of folks got riled up here. 

Thank you so much for implementing this, i appreciate what you have done here 🙌

**Comment by WhySoBad** [comment]
> [@WhySoBad](https://github.com/WhySoBad) Double check that you've enabled the API compatibility layer by merging the following into your zot config:
> 
> {
>   "http": {
>     "compat": ["docker2s2"]
>   }
> }
> 
> Without this ^, I also get invalid manifest errors on the Docker media type. However, with this ^, I am able to push from my local Docker daemon:
> 
> ![Image](https://github.com/user-attachments/assets/d933392d-759f-4857-8adb-510122cc1817)

Thanks for the reply. I caught up on this issue a few days ago and realized it didn't work due to my custom config not having this entry. However, I forgot to resolve my comment here.

**Comment by andaaron** [comment]
https://github.com/project-zot/zot/pull/2903 has been merged this week. It adds options to preserve Docker media types (and implicitly the digests) when using the sync feature.
