### ISSUE TITLE
Submit preliminary OCI distribution-spec conformance results

### ISSUE THREAD

**Issue by jdolitsky** [project-zot/zot#73]
Hello - please see these instructions for how to certify zot as OCI-conformant: https://github.com/opencontainers/oci-conformance/blob/master/instructions.md

As the distribution spec has not yet reached 1.0, please simply use "v1.0-pre" as the spec version number. For example, open a PR on [opencontainers/oci-conformance](https://github.com/opencontainers/oci-conformance) containing the following files:
```
distribution-spec/v1.0-pre/zot/README.md
distribution-spec/v1.0-pre/zot/report.html
distribution-spec/v1.0-pre/zot/junit.xml
distribution-spec/v1.0-pre/zot/PRODUCT.yaml
```

Please reach out if you have any questions.

**Comment by rchincha** [comment]
https://github.com/opencontainers/oci-conformance/tree/main/distribution-spec/v1.0/zot

Also part of our ci/cd pipeline to ensure none of our PRs break conformance.
