### ISSUE TITLE
storage: refactor pkg/storage

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#730]
**Describe the bug**

Currently, we have modeled different storage backends as completely independent modules. However, most of the code is identical (investigate if this is true), so perhaps refactor as common code and backend-specific code.

**Comment by rchincha** [comment]
Create a single `ImageStore` with different `Backend`. Remove the pkg/storage/storage.go interface.

`
type ImageStore stuct {
...
BackingStore *driver
...
}

type Cache struct {
...
BackingStore *driver
...
}
`

**Comment by rchincha** [comment]
Analyze the code carefully though.

**Comment by rchincha** [comment]
Also evaluate if we add more cloud backends, would this refactor be detrimental?

**Comment by peusebiu** [comment]
Couldn't use the storage driver for filesystem, there are a lot of places where things are done differently. Let's say that this can be solved, but the storage driver use file.Sync() and file.Flush() at every write, and from my understanding we don't want that, currently we have a 'commit' flag in the config for this.
