### ISSUE TITLE
scrub: also create a media-type scrub method instead of just repo

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#734]
**Is your feature request related to a problem? Please describe.**

As we add more media-types (now we also support manifest index which is a container of images), it needs to be scrubbed differently.

**Describe the solution you'd like**

foreach manifest in a repo:
   switch manifest.mediaType:
        case ImageManifest: // we already support this
        case ImageIndex: // unpack the manifest, iterate over each manifest and scrub them, this is NEW
        case ArtifactType: // something else, this is future

**Comment by rchincha** [comment]
Related to issue https://github.com/project-zot/zot/issues/640

**Comment by andaaron** [comment]
The image index case was covered in https://github.com/project-zot/zot/pull/1031.
The artifact case is postponed for now.

**Comment by andaaron** [comment]
Since the artifact manifest was removed, the only remaining requirement is to also take the image manifest 'Subject' into consideration when running scrub.

**Comment by andaaron** [comment]
Done in https://github.com/project-zot/zot/pull/1845
