### ISSUE TITLE
sync: also create a media-type sync method instead of just repo

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#735]
**Is your feature request related to a problem? Please describe.**

We support image index manifest type (ispec.MediaTypeImageIndex) which is a list of manifests, so when sync'ing make sure that all the inner manifests are also downloaded.

**Comment by rchincha** [comment]
Related to issue #640

**Comment by andaaron** [comment]
Done in https://github.com/project-zot/zot/pull/847
