### ISSUE TITLE
http Range Support for Image Pull

### ISSUE THREAD

**Issue by mwopfner** [project-zot/zot#762]
**Is your feature request related to a problem? Please describe.**
I try to pull an artifact (binary file, not an image layer) from the repository. This perfectly works if I use `wget` but if I do it with the desired tool I get an http response that states: "range requests not supported by server".

**Describe the solution you'd like**
`zot` should support http `Range` as described in the spec use case "Resumeable Pull".
https://github.com/opencontainers/distribution-spec/blob/main/spec.md#resumable-pull

Unfortunately there is no detailed description for "Pulling a blob in chunks" as it is there for Pushing but I think the use case clearly states that this is a feature that should exist.

**Describe alternatives you've considered**
I verified that pulling the complete artifact works by using `wget` but the tool that must actually pull the artifact uses http `Range` because it does it in a streaming manner.

**Additional context**
The logs I get from `zot` are:
```
{"level":"info","module":"http","clientIP":"192.168.111.93:50614","method":"GET","path":"/v2/linux-os/blobs/sha256:34d8f27da12f02a3a57653c19b44815fe53cc9fde16a03ec242dc2fac673a8ac","statusCode":200,"latency":"690.051µs","bodySize":720896,"headers":{"Accept":["*/*"],"Range":["bytes=0-3"],"User-Agent":["rauc/1.7"]},"goroutine":29,"caller":"zotregistry.io/zot@v1.4.1/pkg/api/session.go:132","time":"2022-08-30T08:08:13.978160735+02:00","message":"HTTP API"}
{"level":"error","error":"write tcp 192.168.111.93:8080->192.168.111.93:50616: write: broken pipe","goroutine":45,"caller":"zotregistry.io/zot@v1.4.1/pkg/api/routes.go:1334","time":"2022-08-30T08:08:14.987854242+02:00","message":"copying data into http response"}
```
I looked at the specific code lines and as I see it `zot` actually does not support http `Range` requests. Is this correct?

**Comment by rchincha** [comment]
> zot should support http Range as described in the spec use case "Resumeable Pull".
> https://github.com/opencontainers/distribution-spec/blob/main/spec.md#resumable-pull

@mwopfner Thanks for trying out zot and reporting this issue. We will fix this.

Just curious, is this an embedded device use case? None of standard tooling that we are aware of has this requirement.

**Comment by mwopfner** [comment]
@rchincha Yes, your are correct, it is an embedded device which uses http `Range` to avoid a complete download of the artifact to the filesystem. 
Currently I have disabled the streaming support, so I can use zot but the support of http `Range` later on would be great.

**Comment by rchincha** [comment]
We have a PR #765 code-ready (merge is pending writing/passing ci/cd tests)
But if you want to try the patch,

```
https://patch-diff.githubusercontent.com/raw/project-zot/zot/pull/765.patch | git apply
```

Manual tests:

```
 $ curl -v http://localhost:8080/v2/busybox/blobs/sha256:84016b10d6ad983b67f95a3f6cfc993e074923a865840adec4c4ebe7fd51c511 -H "Range: bytes=10-100"
 
 * Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v2/busybox/blobs/sha256:84016b10d6ad983b67f95a3f6cfc993e074923a865840adec4c4ebe7fd51c511 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Range: bytes=10-100
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 206 Partial Content
< Access-Control-Allow-Headers: Authorization,content-type
< Access-Control-Allow-Methods: HEAD,GET,POST,OPTIONS
< Access-Control-Allow-Origin: *
< Content-Length: 90
< Content-Type: */*
```

**Comment by rchincha** [comment]
@mwopfner Also, is there a minimal setup that we can put in our ci/cd pipeline in order to test this path so that rauc stays supported.

**Comment by mwopfner** [comment]
@rchincha I tested the patch but it did not work out of the box. I added a review to the PR #765, which show the changes I had to made to get it working.

One finding was that a range starting with 0 returned the complete blob and not the first 100 bytes.
```
 curl -v http://localhost:8080/v2/busybox/blobs/sha256:84016b10d6ad983b67f95a3f6cfc993e074923a865840adec4c4ebe7fd51c511 -H "Range: bytes=10-100"
 
 * Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /v2/busybox/blobs/sha256:84016b10d6ad983b67f95a3f6cfc993e074923a865840adec4c4ebe7fd51c511 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.81.0
> Accept: */*
> Range: bytes=0-100
```

For my use case [Single part ranges](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#single_part_ranges) are enough, but maybe [Multipart ranges](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#multipart_ranges) and [Conditional range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#conditional_range_requests) should also be supported in the future?

I don't think a good minimal setup with rauc is possible because there is no way to just download the artifact. It provided methods directly installs the artifact to a disk partition which would need a complicated qemu setup.

**Comment by rchincha** [comment]
Are you referring to this test?
https://github.com/rauc/rauc/blob/master/qemu-test

**Comment by mwopfner** [comment]
@rchincha I have an own test setup with rauc an qemu where I test my complete system image (multiple partitions) with an A/B rootfs setup including the bootloader, etc. This is a very large overhead (and a lot of things that can cause a failure of the test) to just test the http range support of zot.

The https://github.com/rauc/rauc/blob/master/qemu-test seams to provide a test framework for rauc (I have not used it). I looked into the tests but the tests I have seen are mostly for partition and update bundle management. I'm not sure how/where the actual http range download is tested.

As an alternative I look for a simple tool that downloads a file via http range but it is surprisingly difficult to find one. I hopped to find some compliance test tool for http but could not find anything. The best solution I came up is to use [curl](https://everything.curl.dev/http/ranges), which is of course not optimal.

**Comment by rchincha** [comment]
> @rchincha Yes, your are correct, it is an embedded device which uses http `Range` to avoid a complete download of the artifact to the filesystem (The used tool is actual https://rauc.io/ and the artifact is a custom linux os rootFS which should directly be streamed to a disk partition). Currently I have disabled the streaming support, so I can use zot but the support of http `Range` later on would be great.

@mwopfner if possible, could you share what kind of h/w specs do these IoT/embedded devices have in terms of CPU, memory and disk? Would help us guide future engineering decisions.

**Comment by mwopfner** [comment]
@rchincha The current PC (used on a mobile robot platform) is a Core i5 with 8Gb RAM and 32Gb SSD. Later one we also plan to run it on some ARM Processors (iMX6 or similar). So the devices have some computation power and the use of `Range` arises from the fact that our rootfs is read only and we do not have a lot of writable storage where we can temporarily store the image. It is directly written to a disk partition.

**Comment by rchincha** [comment]
@mwopfner https://github.com/project-zot/zot/releases/tag/v1.4.2 is now out which should have this feature officially. Pls do try and let us know how it goes.

**Comment by mwopfner** [comment]
I have tested the new version and now everything works as expected. Thanks for the fast fix. :+1:

**Comment by rchincha** [comment]
Hi @mwopfner, how has your experience with zot been so far? Just FYI, zot has been accepted as a cncf sandbox project (https://zotregistry.io) and we are now looking to track project "adoptions".
