### ISSUE TITLE
Remove usage of deprecated library io/ioutil

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#767]
See details in https://pkg.go.dev/io/ioutil

```
Deprecated: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.
```

**Comment by slab713** [comment]
Hello everyone, just tested how PRs work. First time. If you want, I can update the rest, too.

**Comment by andaaron** [comment]
Hi @slab713, and thank you for contributing to the project!
I will take a look at your PR and reply there.

**Comment by rchincha** [comment]
Closing issue since PR is merged.
