### ISSUE TITLE
zli cve should show an error if the image does not exist

### ISSUE THREAD

**Issue by mikemccracken** [project-zot/zot#803]
**Describe the bug**
zli just prints nothing for missing images, 
```
$ zli cve aci-zot -I c3/minbase:1.0.1955555
ID                SEVERITY  TITLE
$ echo $?
0
```

**Expected behavior**

an error message to distinguish between missing images and images with no CVEs would be useful

**Comment by aokirisaki** [comment]
I tried recreating the issue and if the image doesn't exists I get this output:
```
$ bin/zli-linux-amd64 cve config-multiple-cve5000 -I img:tag
Error: repository: not found
```

And if the image exists but doesn't have CVEs, I get no output, not even the header:
```
$ bin/zli-linux-amd64 cve config-multiple-cve5000 -I busybox:latest
```
