### ISSUE TITLE
bug: discover endpoint depends on search extension to be active

### ISSUE THREAD

**Issue by chofnar** [project-zot/zot#860]
https://github.com/project-zot/zot/blob/1afc5c8c3fc8f4b4016bcda807ef7166f2c44ff9/pkg/extensions/extension_search.go#L103-L108
This prevents the discovery of other extensions if search is not enabled.

**Comment by rchincha** [comment]
Not a bug! `search` is the only extension exposed via HTTP and without that exposing discover API is not useful.
