### ISSUE TITLE
Investigate how to add annotations on image indexes (multi-arch images)

### ISSUE THREAD

**Issue by andaaron** [project-zot/zot#933]

**Comment by nicoldr** [comment]
Investigate how to add annotations on image indexes (multi-arch images)
- skopeo --insecure-policy copy --format=oci --dest-tls-verify=false --multi-arch=all docker://public.ecr.aws/docker/library/busybox:latest docker://127.0.0.1:8080/busybox:latest
**Podman**: steps used:
* --tls-verify=false flag is not available in podman in the version we use and the ones we can install on linux
* added insecure registry:
        sudo cat > /etc/containers/registries.conf.d/myregistry.conf <<EOF
          [[registry]]
          location = "localhost:8080"
          insecure = true
          EOF
- Created image to hold manifest list: 
        podman manifest create imageindex:v1 docker://localhost:8080/busybox:latest --all
- Pulling busybox:latest
        podman manifest push localhost/imageindex:v1 docker://localhost:8080/imageindexdocker:v1
- Trying to annotate:
        podman manifest annotate --annotation annotation=value localhost/imageindexdocker:v1 sha256:80325e14c405a4e951f94d5bff372c4282c9b9e854c0ca4cf9d04e99c5bf97f0
        podman manifest annotate --annotation annotation=value localhost/imageindex:v1
        podman manifest annotate --annotation annotation=value localhost/imageindex:v1 9a41f89ada0f98333192ebd6f2524864c115e31a6bf03c3bac5f8ef89c8f5622
Error: invalid image digest "9a41f89ada0f98333192ebd6f2524864c115e31a6bf03c3bac5f8ef89c8f5622": invalid checksum digest format

Conclusion: Podman does not support annotating image indexes on multi arch images.

**Regctl**: 
These are the only index available opperations: 
```
Index Commands
The index command creates or manages OCI Indexes and Manifest Lists.
Usage:
  regctl index [command]

Available Commands:
  add         add an index entry
  create      create an index
  delete      delete an index entry

The create command is used to create a new Index and optionally include an initial set of manifests. The add and delete commands are used to add and remove manifests from the Index. When adding manifests to an Index, references in other repositories will first be copied to the local repository. The platform will automatically be added when an image has a config containing those fields.
```
--> You can see here that "add" only adds a manifest entry to the index. 

In docs, below these, are artifacts commands, and here it is specified that put command can be used to add annotations, but the media type must be application/vnd.oci.image.manifest.v1+json:
`The put command uploads an artifact to the registry. The artifact may be pushed with it's own tag or by digest using --by-digest which ignores the tag value. The artifact may be pushed with the subject field using the --subject option, associating the artifact with another manifest which can be shown with the regctl artifact list command. The --media-type must be either application/vnd.oci.image.manifest.v1+json or application/vnd.oci.artifact.manifest.v1+json, but many registries will not support the latter type. The --artifact-type option sets the artifactType on the artifact manifest or the config mediaType on the image manifest. The config json may also included for image manifests. Each file should have a media type passed in the same order on the command line. A single file may be pushed using stdin. To set annotations on the manifest, use --annotation name=value, and repeat the flag for additional annotations. `

Source: https://github.com/regclient/regclient/blob/main/docs/regctl.md

**Comment by andaaron** [comment]
For the record, how to build multiarch with porman: https://podman.io/blogs/2021/10/11/multiarch.html

**Comment by andaaron** [comment]
Let's close this. Will follow up in a separate issue later.
