### ISSUE TITLE
Add minimal image tag to home readme

### ISSUE THREAD

**Issue by dtzar** [project-zot/zot#935]

**Comment by rchincha** [comment]
@dtzar feedback appreciated and noted.

We are refactoring our documentation UX to address these concerns.

For the time being,
https://docs.zotregistry.io/zot-docs-1/1.0/general/artifacts.html#_full_and_minimal_binary_images

**Comment by dtzar** [comment]
@rchincha It seems there is some problem here where the `-minimal` version is bigger than the `:latest`.

```
REPOSITORY                                                TAG                                                                          IMAGE ID       CREATED         SIZE
ghcr.io/project-zot/zot-minimal-linux-amd64               v1.4.3-rc5                                                                   2fffc0422b3d   24 hours ago    116MB
ghcr.io/project-zot/zot-linux-amd64                       v1.4.3-rc5                                                                   81e94ffa1b6a   24 hours ago    83.2MB
```

And when I try to download the `zot-linux-amd64-minimal` it doesn't work.

```
docker pull ghcr.io/project-zot/zot-linux-amd64-minimal:v1.4.3-rc5
Error response from daemon: Head "https://ghcr.io/v2/project-zot/zot-linux-amd64-minimal/manifests/v1.4.3-rc5": denied
```

**Comment by rchincha** [comment]
@dtzar looking into this. Gives me a different error though.

**Comment by rchincha** [comment]
```
docker pull ghcr.io/project-zot/zot-minimal-linux-amd64:v1.4.3-rc5
v1.4.3-rc5: Pulling from project-zot/zot-minimal-linux-amd64
8fdb1fc20e24: Pull complete
fda4ba87f6fb: Pull complete
8396d2813bee: Pull complete
f071b1358162: Pull complete
90f26b50b674: Pull complete
Digest: sha256:e00612564fbf7fa3f50577f52134935845711dd6d447770726278040db26137f
Status: Downloaded newer image for ghcr.io/project-zot/zot-minimal-linux-amd64:v1.4.3-rc5
ghcr.io/project-zot/zot-minimal-linux-amd64:v1.4.3-rc5
```

**Comment by dtzar** [comment]
I showed how I successfully copied that image above but it was 116 MB versus 82.  On the zot releases page it shows this is 32 MB: https://github.com/project-zot/zot/releases/download/v1.4.3-rc5/zot-linux-amd64-minimal which is why I tried the `-minimal` at the end.

**Comment by rchincha** [comment]
This looks like a bug! The container image contains both the full and minimal. Fixing.

**Comment by rchincha** [comment]
@dtzar, we have fixed the minimal container image. The fix should be available when we cut the next rc/final release. Thanks for reporting it.
