### ISSUE TITLE
[Feat]: add support for OpenID connect authN

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#978]
### Is your feature request related to a problem? Please describe.

Add OpenID based authN/Z apart from the mechanisms currently available.

**Comment by rchincha** [comment]
https://github.com/coreos/go-oidc

**Comment by rchincha** [comment]
GitHub has not implemented a well-known configuration endpoint, so you will need to disable the Discover endpoints field and specify the endpoints manually. The values for these fields are:

    Authorization endpoint - https://github.com/login/oauth/authorize

    Token endpoint - https://github.com/login/oauth/access_token

    Userinfo endpoint - https://api.github.com/user

You will need to specify user:email as a Scope for your application.

**Comment by rchincha** [comment]
https://docs.gitlab.com/ee/integration/openid_connect_provider.html

**Comment by rchincha** [comment]
Would approach this in two steps. Although we model an array of providers, we first support a single openID provider. Then scope the provider with a prefix to route the authN request accordingly.

**Comment by andaaron** [comment]
Fixed in #1381
