### ISSUE TITLE
[Feat]: Add a group mechanism for authZ

### ISSUE THREAD

**Issue by voor** [project-zot/zot#983]
### Is your feature request related to a problem? Please describe.

Providing unique permissions to individual users works at a small scale when you're managing dozens of users, but once you're dealing with larger amounts of users you need a group mechanism that can automatically apply users to different groups and assign permissions to groups rather than individuals.  Additionally, this eliminates the need for shared accounts like an `admin` account or similar, which is typically a security violation.

### Describe the solution you'd like

As an authenticated user I am already applied to the `Default` group, which is the failover for when the individual does not have a user based policy.  Add another option for `groups` inside the policies type that can apply policies to entire groups.

```json
"http": {
...
  "accessControl": {
    "**": {
      "policies": [{
        "users": ["charlie"],
        "groups": ["admins","developers"],
        "actions": ["read", "create", "update"]
      }],
      "defaultPolicy": ["read", "create"]
    },
    "tmp/**": {
      "defaultPolicy": ["read", "create", "update"]
    },
    "infra/*": {
      "policies": [{
          "users": ["alice", "bob"],
          "groups": ["maintainers","platformteam"],
          "actions": ["create", "read", "update", "delete"]
        },
        {
          "users": ["mallory"],
          "actions": ["create", "read"]
        }
      ],
      "defaultPolicy": ["read"]
    },
    "repos2/repo": {
      "policies": [{
          "users": ["bob"],
          "groups": ["sparkle_team","repo2_team"],
          "actions": ["read", "create"]
        },
        {
          "users": ["mallory"],
          "actions": ["create", "read"]
        }
      ],
      "defaultPolicy": ["read"]
    },
    "adminPolicy": {
      "users": ["admin"],
      "groups": ["admins","developers"],
      "actions": ["read", "create", "update", "delete"]
    }
  }
```

### Additional context

Coordinating this with https://github.com/project-zot/zot/issues/978 would provide an easy mechanism to discovery user-group pairings without needing to create an internal configuration to match a user to a group.

**Comment by alexstan12** [comment]
Hi @voor ! In the solution you've described above, where would the **group** value come from? Is it from the ID token retrieved from OIDC flow?
If so, then 'group' isn't really a default claim on this token and would require a modification on the provider side ( e.g. Github, Gitlab, Google ) which I don't think it's possible, since we're not implementing the provider side of the OIDC flow

**Comment by voor** [comment]
This is usually from the [userinfo](https://developers.google.com/identity/openid-connect/openid-connect#obtainuserinfo) endpoint after you have an ID token.
