### ISSUE TITLE
[Refactor]: Cleanup/simplify test cases by moving common datapath code under pkg/test

### ISSUE THREAD

**Issue by rchincha** [project-zot/zot#989]
### Is your feature request related to a problem? Please describe.

Our unit tests have copy-n-paste code bloat making them hard to read/verify. For example, we manually/explicitly create each config and data blob and upload, etc.

### Describe the solution you'd like

Define common subroutines under pkg/test and use these. Will make our life a lot easier both for UT devs and reviewers.

**Comment by andaaron** [comment]
Partially covered in https://github.com/project-zot/zot/pull/1041, and a few other minor PRs leveraging it. Need to assess what else needs to be done.
